#!/usr/bin/env python3
"""Build the small stock-MOS filesystem reproducer without touching hardware."""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import yaml

TASK=Path(__file__).resolve().parent
ROOT=TASK.parents[2]


def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,required=True)
    parser.add_argument('--toolchain',type=Path,default=ROOT.parent/'mos-agondev/toolchains/agondev')
    args=parser.parse_args()
    output=args.output.resolve();output.mkdir(parents=True)
    project=TASK/'fixture';identity=json.loads((project/'identity.json').read_text())
    now=datetime.now(timezone.utc)
    build_id=identity['source_identity']+now.strftime('-b%Y-%m-%d-%H-%M-%SZ')
    header=project/'build/build_identity.h';header.parent.mkdir(exist_ok=True)
    header.write_text('// Generated by REMED-003/build.py; do not edit.\n'
                      f'#define FS_BUILD_ID "{build_id}"\n#define FS_STATUS "{identity["status"]}"\n')
    inputs={str(p.relative_to(ROOT)):sha(p) for p in [Path(__file__),project/'Makefile',project/'identity.json',project/'src/main.c']}
    with (output/'build.log').open('w') as log:
        for target in ('clean','all'):
            subprocess.run(['make',f'AGONDEV_TOOLCHAIN={args.toolchain.resolve()}',target],cwd=project,
                           stdout=log,stderr=subprocess.STDOUT,check=True)
    files=[]
    for suffix in ('bin','map'):
        path=output/(build_id+'.'+suffix)
        shutil.copy2(project/('bin/FSCHECK.'+suffix),path)
        files.append(dict(filename=path.name,sha256=sha(path),role=suffix))
    content=(output/files[0]['filename']).read_bytes()
    if content[0x40:0x45] not in (b'MOS\x00\x01',b'MOS\x01\x01') or build_id.encode() not in content:
        raise ValueError('Invalid executable or identity')
    (output/'build-manifest.yaml').write_text(yaml.safe_dump(dict(schema_version=1,
        build=dict(identity,build_id=build_id,created_at=now.isoformat()),
        provenance=dict(commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),
                        dirty=bool(subprocess.check_output(['git','status','--porcelain'],cwd=ROOT)),
                        source_sha256=inputs,compiler_sha256=sha(args.toolchain/'bin/ez80-none-elf-clang')),
        outputs=files),sort_keys=False))
    print(build_id)


if __name__=='__main__':main()
