#!/usr/bin/env python3
"""Rejected historical payload generator for the retired P4 ZDI recovery.

The old implementation remains below to explain the ignored payload retained
with predecessor evidence. Invocation fails before reading or writing files.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys
import textwrap
import zlib


RETIRED_MESSAGE = (
    "the PORT-008 P4-to-ZDI recovery is retired; this historical generator "
    "must not create a new flash payload"
)


def read_verified(path: Path, expected_sha256: str, role: str) -> bytes:
    payload = path.read_bytes()
    actual = hashlib.sha256(payload).hexdigest()
    if actual != expected_sha256:
        raise SystemExit(
            f"{role} SHA-256 mismatch: expected {expected_sha256}, got {actual}"
        )
    return payload


def byte_array(name: str, payload: bytes) -> str:
    rows = []
    for offset in range(0, len(payload), 16):
        values = ", ".join(f"0x{value:02X}" for value in payload[offset : offset + 16])
        rows.append(f"    {values},")
    return f"alignas(4) inline constexpr uint8_t {name}[] = {{\n" + "\n".join(rows) + "\n};"


def main() -> int:
    sys.stderr.write(RETIRED_MESSAGE + "\n")
    return 2

    # Historical implementation below is intentionally unreachable.
    parser = argparse.ArgumentParser()
    parser.add_argument("--mos", required=True, type=Path)
    parser.add_argument("--mos-sha256", required=True)
    parser.add_argument("--flash-agent", required=True, type=Path)
    parser.add_argument("--flash-agent-sha256", required=True)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    mos = read_verified(args.mos, args.mos_sha256, "EMOS")
    agent = read_verified(
        args.flash_agent, args.flash_agent_sha256, "agon-recovery flash agent"
    )
    if not 1 <= len(mos) <= 0x40000:
        raise SystemExit(f"EMOS payload has unsafe size {len(mos)}")
    if len(agent) != 90:
        raise SystemExit(f"unexpected agon-recovery flash-agent size {len(agent)}")

    rendered = textwrap.dedent(
        f"""\
        // Generated by generate-recovery-payload.py. DO NOT EDIT OR COMMIT.
        #pragma once
        #include <cstddef>
        #include <cstdint>

        namespace agon_extender::diagnostic::recovery_payload {{
        inline constexpr char kMosSha256[] = "{args.mos_sha256}";
        inline constexpr char kFlashAgentSha256[] = "{args.flash_agent_sha256}";
        inline constexpr uint32_t kMosCrc32 = 0x{zlib.crc32(mos) & 0xFFFFFFFF:08X}U;
        inline constexpr uint32_t kFlashAgentCrc32 = 0x{zlib.crc32(agent) & 0xFFFFFFFF:08X}U;
        """
    )
    rendered += byte_array("kMosImage", mos) + "\n\n"
    rendered += byte_array("kFlashAgent", agent) + "\n"
    rendered += textwrap.dedent(
        """
        inline constexpr size_t kMosSize = sizeof(kMosImage);
        inline constexpr size_t kFlashAgentSize = sizeof(kFlashAgent);
        }  // namespace agon_extender::diagnostic::recovery_payload
        """
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(
        f"generated {args.output}: EMOS {len(mos)} bytes CRC32 "
        f"{zlib.crc32(mos) & 0xFFFFFFFF:08x}; agent {len(agent)} bytes"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
