#!/usr/bin/env python3
"""Build an identified SD-only benchmark bundle; never access removable media."""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import yaml

TASK = Path(__file__).resolve().parents[1]
ROOT = TASK.parents[2]
PROJECT = TASK / 'fixture'
EMOS = 'agon-emos-v0.1.12-b2026-09-10-03-50-35Z'
EDP = 'uart-excom-console-r07-b2026-09-10-06-31-58Z'


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def with_filesystem_probe(startup):
    insertion=b'EMOS KEYINPUT extender\r\n'
    if startup.count(insertion)!=1: raise ValueError('Unexpected startup shape')
    return startup.replace(insertion,b'LOAD /extender/fscheck/FSCHECK.BIN\r\nRUN\r\n'+insertion,1)


def sources():
    return {str(p.relative_to(ROOT)): sha(p) for p in sorted(TASK.rglob('*'))
            if p.is_file() and not any(x in p.parts for x in ('bin', 'obj', 'build', '__pycache__'))}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--toolchain', type=Path, default=ROOT.parent/'mos-agondev/toolchains/agondev')
    parser.add_argument('--probe', action='store_true', help='Startup runs the short pixel-reply diagnostic')
    args = parser.parse_args()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=False)
    identity = json.loads((PROJECT/'identity.json').read_text())
    now = datetime.now(timezone.utc)
    build_id = identity['source_identity'] + now.strftime('-b%Y-%m-%d-%H-%M-%SZ')
    toolchain = args.toolchain.resolve(strict=True)
    before = sources()
    header = PROJECT/'build/build_identity.h'
    header.parent.mkdir(exist_ok=True)
    header.write_text('// Generated by AUDIT-005/scripts/build.py; do not edit.\n' + ''.join(
        f'#define {key} "{value}"\n' for key, value in {
            'BENCH_BUILD_ID': build_id, 'BENCH_STATUS': identity['status'],
            'BENCH_EMOS': EMOS, 'BENCH_EDP': EDP}.items()))
    with (output/'build.log').open('w') as log:
        for target in ('clean', 'all'):
            subprocess.run(['make', f'AGONDEV_TOOLCHAIN={toolchain}', target], cwd=PROJECT,
                           stdout=log, stderr=subprocess.STDOUT, check=True)
    if sources() != before:
        raise RuntimeError('Inputs changed during build')
    files = []
    for suffix in ('bin', 'map'):
        destination = output/(build_id+'.'+suffix)
        shutil.copyfile(PROJECT/('bin/UPBENCH.'+suffix), destination)
        files.append(dict(filename=destination.name, sha256=sha(destination),
                          size_bytes=destination.stat().st_size, role=suffix))
    binary = output/files[0]['filename']
    content = binary.read_bytes()
    if content[0x40:0x45] not in (b'MOS\x00\x01', b'MOS\x01\x01') or build_id.encode() not in content:
        raise RuntimeError('Missing ADL executable header or build identity')
    autoexec = ('VDU 22 3\nLOAD /bin/EMBOOT.BIN\nRUN\nEMOS KEYINPUT extender\n'
                'VDU 22 0\nEMOS EXCOM --keep-display\nVDU 22 0\n'
                'CD /extender/uartbench\nLOAD UPBENCH.BIN\nRUN\n')
    if args.probe:
        autoexec=autoexec.removesuffix('RUN\n')+'RUN . probe\n'
    (output/'autoexec.txt').write_bytes(autoexec.replace('\n', '\r\n').encode())
    files.append(dict(filename='autoexec.txt',sha256=sha(output/'autoexec.txt'),role='autoexec'))
    manifest = dict(schema_version=1, build=dict(identity, build_id=build_id, created_at=now.isoformat()),
                    provenance=dict(commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),
                        dirty=bool(subprocess.check_output(['git','status','--porcelain'],cwd=ROOT)),
                        source_sha256=before, compiler_sha256=sha(toolchain/'bin/ez80-none-elf-clang')),
                    baseline=dict(emos=EMOS, edp=EDP, mainboard_vdp='2.16.0'), outputs=files,
                    scope='Exploratory SD application; no firmware change or hardware qualification claim')
    (output/'build-manifest.yaml').write_text(yaml.safe_dump(manifest, sort_keys=False))
    print(build_id)
    print(output)


if __name__ == '__main__':
    main()
