"""Stamp a new paired fixture build; never reuse an identity for changed bytes."""
from datetime import datetime,timezone
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
identity=json.loads((root.parent/'identity.json').read_text())
identity['build_id']=identity['source_identity']+datetime.now(timezone.utc).strftime('-b%Y-%m-%d-%H-%M-%SZ')
(root/'build').mkdir(exist_ok=True)
(root/'build/paired-identity.json').write_text(json.dumps(identity,indent=2)+'\n')
(root/'build/paired-identity.inc').write_text('; Generated by build_identity.py; do not edit.\npaired_identity:\n    db "'+identity['build_id']+' ('+identity['status']+')",13,10\npaired_identity_end:\n')
