"""Read retained evidence; write only this debrief's derived JSON and tables."""
from pathlib import Path
import csv, hashlib, importlib.util, json, re, statistics, sys
ROOT = Path(__file__).resolve().parents[4]
HERE = Path(__file__).resolve().parent
N = ROOT/'docs/tasks/QUAL-003/nurples-parity'
E = ROOT/'docs/tasks/QUAL-003/timing/results/e09-unattended'
sys.path.insert(0,str(N))
from analyze_refresh_trace import analyze
from analyze_native_wait import read as native_read
sources={}
def get(p):
 sources[str(p.relative_to(ROOT))]=hashlib.sha256(p.read_bytes()).hexdigest()
 return json.loads(p.read_text())
def pct(a,b):return 100*(b/a-1) if a else None
def table(headers,rows):
 return '\n'.join(['| '+' | '.join(headers)+' |','|'+'|'.join(['---']+['---:']*(len(headers)-1))+'|']+['| '+' | '.join(map(str,row))+' |' for row in rows])+'\n'
spec=importlib.util.spec_from_file_location('validator',E.parents[1]/'scripts/read_results.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
validated=m.validate(E/'GQT009.CSV',E/'corpus.json')
sources[str((E/'GQT009.CSV').relative_to(ROOT))]=hashlib.sha256((E/'GQT009.CSV').read_bytes()).hexdigest()
raw=list(csv.DictReader(x for x in (E/'GQT009.CSV').read_text().splitlines() if not x.startswith('#')))
e=get(E/'analysis.json');assert e['intervals']==624 and e['snapshot_delta']==0
# Independently recompute each saved rendering median/count, not trusting summary prose.
for rec in e['records']:
 for metric,label in [(1,'elapsed'),(2,'primitive'),(4,'software_sprite')]:
  for route,dev in [(0,'vdp'),(1,'edp')]:
   rs=[r for r in raw if r['case']==rec['case'] and r['repeat'] in ('1','2','3') and r['detail']=='1' and r['route']==str(route) and r['phase']=='draw' and r['metric']==str(metric)]
   assert len(rs)==3 and all(r['status']=='0' for r in rs)
   v=statistics.median(int(r['value'])/1000 for r in rs)
   assert abs(v-rec[dev+'_'+label]['median_ms'])<1e-10
   assert [int(r['count']) for r in rs]==rec[dev+'_'+label]['counts']
matched=get(N/'results/matched-refresh-first.json')
print('Matched keys',list(matched))
base={k:v['mainboard'] for k,v in matched.items() if isinstance(v,dict) and 'mainboard' in v}
assert len(base)==2
mainraw=N/'results/refresh-mainboard.log';sources[str(mainraw.relative_to(ROOT))]=hashlib.sha256(mainraw.read_bytes()).hexdigest()
for b in base.values():
 fresh=analyze(mainraw.read_text(),b['nonce'],2400,'mainboard')
 for key in ['submitted','completed','maximum_pending_refreshes','completion_intervals','completed_fps','enqueue_to_completion']:assert fresh[key]==b[key],key
out={'scope':'Derived from retained evidence only; no hardware run','e09':{'validated_intervals':624,'snapshot_delta':0,'probe_differences':8},'sources':sources}
rows=[];nr=[]
for rev in [38,39,40,41,42,43]:
 d=get(N/f'results/verified-r{rev}-output.json')
 for label,v in d.items():
  if not isinstance(v,dict) or 'completion_trace' not in v:continue
  t=v['completion_trace'];hw='hw' in label.lower();key=next(k for k in base if ('hw' in k.lower())==hw);b=base[key]
  assert t['submitted']==t['completed']==2400
  rawtrace=N/f'results/refresh-r{rev}.log';sources[str(rawtrace.relative_to(ROOT))]=hashlib.sha256(rawtrace.read_bytes()).hexdigest()
  fresh=analyze(rawtrace.read_text(),t['nonce'],2400)
  for metric in ['submitted','completed','maximum_pending_refreshes','completion_intervals','completed_fps','enqueue_to_completion']:assert fresh[metric]==t[metric],(rev,label,metric)
  x=dict(revision=rev,label=label,path='HW' if hw else 'SW',stock=b,trace=t,mean_duration_difference_pct=pct(b['completion_intervals']['mean_ms'],t['completion_intervals']['mean_ms']),p95_duration_difference_pct=pct(b['completion_intervals']['p95_ms'],t['completion_intervals']['p95_ms']))
  x['gate_mean']=t['completion_intervals']['mean_ms']<=b['completion_intervals']['mean_ms']*1.05;x['gate_p95']=t['completion_intervals']['p95_ms']<=b['completion_intervals']['p95_ms']+1000/120
  nr.append(x)
  rows.append([rev,label,f"{b['completed_fps']:.3f}",f"{t['completed_fps']:.3f}",f"{b['completion_intervals']['mean_ms']:.3f}",f"{t['completion_intervals']['mean_ms']:.3f}",f"{x['mean_duration_difference_pct']:+.2f}%",f"{b['completion_intervals']['p95_ms']:.3f}",f"{t['completion_intervals']['p95_ms']:.3f}",'pass' if x['gate_mean'] and x['gate_p95'] else 'FAIL'])
out['nurples']=nr
sections=['# Recomputed performance tables\n\nGenerated by derive.py from retained evidence. Percentages compare duration to mainboard: 100 × (P4/mainboard − 1). Negative means less time. No new test.\n','## Matched refresh completion history\n\nChronological within this table; individual passes are not repeated qualification. Same 2400-refresh r05 workload, 120 warmup boundaries, 2279 measured intervals.\n',table(['r','Path/run','Stock FPS','P4 FPS','Stock mean ms','P4 mean ms','Δ mean','Stock p95 ms','P4 p95 ms','Single-run gates'],rows)]
for label,title,selected in [('primitive','Native execution scopes',[x for x in e['records'] if x['vdp_primitive']['median_ms']>=0.05]),('software_sprite','Software-sprite scopes',[x for x in e['records'] if x['vdp_software_sprite']['median_ms']>=0.05 and x['vdp_software_sprite']['counts']==x['edp_software_sprite']['counts']]),('elapsed','Upload-containing stage elapsed',[x for x in e['records'] if x['upload_bytes']])]:
 rows=[]
 for x in sorted(selected,key=lambda x:x['edp_'+label]['median_ms']-x['vdp_'+label]['median_ms'],reverse=True):
  a,b=x['vdp_'+label],x['edp_'+label]
  rows.append([x['case'],f"{a['median_ms']:.3f}",f"{b['median_ms']:.3f}",f"{pct(a['median_ms'],b['median_ms']):+.2f}%",'/'.join(map(str,a['counts'])) if label!='elapsed' else x['upload_bytes']])
 sections += ['## '+title+'\n\nWorst signed P4-minus-stock milliseconds first. Medians of three enabled repeats. Scopes overlap; do not add them.\n',table(['Case','Stock ms','P4 ms','Δ duration','Calls per repeat / upload bytes'],rows)]
units=[]
for case,n in [('SCROLL',64),('CLIPROW',64),('COMBINED',64),('BSP25_02',5)]:
 x=next(x for x in e['records'] if x['case']==case);scope='software_sprite' if case=='BSP25_02' else 'primitive';a=x['vdp_'+scope]['median_ms']/n;b=x['edp_'+scope]['median_ms']/n
 units.append(dict(case=case,divisor=n,scope=scope,mainboard_amortized_ms=a,p4_amortized_ms=b,duration_difference_pct=pct(a,b)))
out['amortized_operations']=units
text=(N/'results/native-wait-r44.txt').read_text();sources[str((N/'results/native-wait-r44.txt').relative_to(ROOT))]=hashlib.sha256(text.encode()).hexdigest();native,waits=native_read(text,'b4bcc755f4fc1cec');assert json.loads(json.dumps(native))==get(N/'results/native-wait-r44-analysis.json')
trace=[tuple(map(int,x)) for x in re.findall(r'NPTRACE row (\d+) (\d+) (\d+)',text)];assert len(trace)==2400
pairs=[]
for i in range(121,2400):
 dt=((trace[i][1]-trace[i-1][1])&0xffffffff)/1000;pairs.append(dict(index=i,enqueue_interval_ms=dt,native_acquisition_ms=waits[i][1]/1000,rx_bytes=waits[i][4]))
out['r44_longest_enqueue_intervals']=sorted(pairs,key=lambda x:x['enqueue_interval_ms'],reverse=True)[:12]
out['r44_long_interval_count_over_25ms']=sum(x['enqueue_interval_ms']>25 for x in pairs)
out['r44_long_intervals_native_mean_ms']=statistics.mean(x['native_acquisition_ms'] for x in pairs if x['enqueue_interval_ms']>25)
wire=get(N/'results/wire-r43-analysis.json');out['wire']={k:wire[k] for k in ['acquisition_pass','partial_acquisition_inspection','wire_refresh_intervals','completion_trace','clock_limit','forward_bytes','reverse_bytes','measured_seconds']}
out['wire']['forward_utilization_nominal_pct']=100*wire['forward_bytes']*10/(1152000*wire['measured_seconds'])
get(N/'results/wire-r43-return-packets.json')
out['qualified_transport']=get(ROOT/'docs/tasks/PORT-008/uart-alignment/results/e07p-transport.json')['profiles']['ordinary']
# Native trace summary reconstruction for raw r43 logs is recorded separately by maintained analyzers.
out['sources']=sources
(HERE/'derived.json').write_text(json.dumps(out,indent=2)+'\n');(HERE/'TABLES.md').write_text('\n'.join(sections))
print(json.dumps({'amortized':units,'r44_long_intervals':out['r44_long_interval_count_over_25ms'],'r44_long_native_mean':out['r44_long_intervals_native_mean_ms'],'longest':out['r44_longest_enqueue_intervals'][:4]},indent=2))
