#!/usr/bin/env python3
"""Generate the PORT-008 normal-r01 wiring and LA-03 probe reference.

This task-local generator deliberately derives the drawing from the retained
light2-harness-r01 legacy diagram instead of making that historical evidence
authoritative for current logic-analyzer placement.  Electrical routes remain
those shown by the source drawing; LA-03 probe markers come from the canonical
la03-p4-probe-fixture-r01 profile and map.
"""

from __future__ import annotations

from pathlib import Path


SCRIPT = Path(__file__).resolve()
REPOSITORY = SCRIPT.parents[5]
SOURCE = (
    REPOSITORY
    / "hardware/designs/light2-harness-r01/legacy-evidence/wiring-diagram.svg"
)
OUTPUT = SCRIPT.parent.parent / "normal-forward-wiring-and-probes.svg"


def replace_once(document: str, old: str, new: str) -> str:
    count = document.count(old)
    if count != 1:
        raise RuntimeError(f"expected one source fragment, found {count}: {old[:80]!r}")
    return document.replace(old, new, 1)


def main() -> None:
    document = SOURCE.read_text(encoding="utf-8")

    document = replace_once(
        document,
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n',
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
        '<!-- Generated by scripts/generate-normal-forward-wiring-and-probes.py.\n'
        '     Electrical routes derive from light2-harness-r01 legacy evidence.\n'
        '     Probe placement derives from la03-p4-probe-fixture-r01. -->\n',
    )
    document = replace_once(
        document,
        'viewBox="-150 0 1400 1250"',
        'viewBox="-150 0 1400 1420"',
    )
    document = replace_once(
        document,
        'width="1400"\n   height="1250"',
        'width="1400"\n   height="1420"',
    )
    document = replace_once(
        document,
        'sodipodi:docname="wiring-diagram.svg"',
        'sodipodi:docname="normal-forward-wiring-and-probes.svg"',
    )
    document = replace_once(
        document,
        '     height="1250"\n     fill="#ffffff" />',
        '     height="1420"\n     fill="#ffffff" />',
    )

    ext1_rows = {
        '<rect id="p4-ext1-pin16" x="0" y="104" width="250" height="22" rx="3" fill="#ffffff" stroke="#333333" stroke-width="1.5"/><text x="6" y="119"><tspan font-weight="bold">16</tspan><tspan> GPIO15</tspan></text>':
        '<rect id="p4-ext1-pin16" x="0" y="104" width="250" height="22" rx="3" fill="#ffffff" stroke="#333333" stroke-width="1.5"/><text x="6" y="119"><tspan font-weight="bold">16</tspan><tspan> GPIO15 / FWD_OE_N</tspan></text><circle id="probe-d7-gpio15" cx="237" cy="115" r="7" fill="#6d4c41" stroke="#111111" stroke-width="1.5"/>',
        '<rect id="p4-ext1-pin15" x="0" y="130" width="250" height="22" rx="3" fill="#111111" stroke="#333333" stroke-width="1.5"/><text x="6" y="145" fill="#ffffff"><tspan font-weight="bold">15</tspan><tspan> GPIO14 / CLOCK</tspan></text><circle id="probe-gray-gpio14" cx="237" cy="141" r="7" fill="#808080" stroke="#555555" stroke-width="1.5"/>':
        '<rect id="p4-ext1-pin15" x="0" y="130" width="250" height="22" rx="3" fill="#111111" stroke="#333333" stroke-width="1.5"/><text x="6" y="145" fill="#ffffff"><tspan font-weight="bold">15</tspan><tspan> GPIO14 / CLOCK</tspan></text><circle id="probe-d5-gpio14" cx="237" cy="141" r="7" fill="#d32f2f" stroke="#111111" stroke-width="1.5"/>',
        '<rect id="p4-ext1-pin14" x="0" y="156" width="250" height="22" rx="3" fill="#ffffff" stroke="#333333" stroke-width="1.5"/><text x="6" y="171"><tspan font-weight="bold">14</tspan><tspan> GPIO13 / VALID_N</tspan></text><circle id="probe-purple-gpio13" cx="237" cy="167" r="7" fill="#7b1fa2" stroke="#555555" stroke-width="1.5"/>':
        '<rect id="p4-ext1-pin14" x="0" y="156" width="250" height="22" rx="3" fill="#ffffff" stroke="#333333" stroke-width="1.5"/><text x="6" y="171"><tspan font-weight="bold">14</tspan><tspan> GPIO13 / VALID_N</tspan></text><circle id="probe-d3-gpio13" cx="237" cy="167" r="7" fill="#f57c00" stroke="#111111" stroke-width="1.5"/>',
        '<rect id="p4-ext1-pin13" x="0" y="182" width="250" height="22" rx="3" fill="#808080" stroke="#333333" stroke-width="1.5"/><text x="6" y="197" fill="#ffffff"><tspan font-weight="bold">13</tspan><tspan> GPIO12 / D1</tspan></text><circle id="probe-blue-gpio12" cx="237" cy="193" r="7" fill="#1976d2" stroke="#555555" stroke-width="1.5"/>':
        '<rect id="p4-ext1-pin13" x="0" y="182" width="250" height="22" rx="3" fill="#808080" stroke="#333333" stroke-width="1.5"/><text x="6" y="197" fill="#ffffff"><tspan font-weight="bold">13</tspan><tspan> GPIO12 / UART TX / D1</tspan></text><circle id="probe-d1-gpio12" cx="237" cy="193" r="7" fill="#fbc02d" stroke="#111111" stroke-width="1.5"/>',
        '<rect id="p4-ext1-pin12" x="0" y="208" width="250" height="22" rx="3" fill="#7b1fa2" stroke="#333333" stroke-width="1.5"/><text x="6" y="223" fill="#ffffff"><tspan font-weight="bold">12</tspan><tspan> GPIO11 / D3</tspan></text><circle id="probe-green-gpio11" cx="237" cy="219" r="7" fill="#388e3c" stroke="#555555" stroke-width="1.5"/>':
        '<rect id="p4-ext1-pin12" x="0" y="208" width="250" height="22" rx="3" fill="#7b1fa2" stroke="#333333" stroke-width="1.5"/><text x="6" y="223" fill="#ffffff"><tspan font-weight="bold">12</tspan><tspan> GPIO11 / D3</tspan></text>',
    }
    for old, new in ext1_rows.items():
        document = replace_once(document, old, new)

    ext2_rows = {
        '<rect id="p4-ext2-pin13" x="0" y="182" width="300" height="22" rx="3" fill="#1976d2" stroke="#333333" stroke-width="1.5"/><text x="6" y="197" fill="#ffffff"><tspan font-weight="bold">13</tspan><tspan> GPIO20 / READY_N</tspan></text><circle id="probe-yellow-gpio20" cx="287" cy="193" r="7" fill="#fbc02d" stroke="#555555" stroke-width="1.5"/>':
        '<rect id="p4-ext2-pin13" x="0" y="182" width="300" height="22" rx="3" fill="#1976d2" stroke="#333333" stroke-width="2.5"/><text x="6" y="197" fill="#ffffff"><tspan font-weight="bold">13</tspan><tspan> GPIO20 / READY_N</tspan></text><circle id="probe-d6-gpio20" cx="287" cy="193" r="7" fill="#808080" stroke="#111111" stroke-width="1.5"/>',
        '<rect id="p4-ext2-pin12" x="0" y="208" width="300" height="22" rx="3" fill="#ffffff" stroke="#333333" stroke-width="1.5"/><text x="6" y="223"><tspan font-weight="bold">12</tspan><tspan> GPIO21</tspan></text><circle id="probe-orange-gpio21" cx="287" cy="219" r="7" fill="#f57c00" stroke="#555555" stroke-width="1.5"/>':
        '<rect id="p4-ext2-pin12" x="0" y="208" width="300" height="22" rx="3" fill="#ffffff" stroke="#333333" stroke-width="1.5"/><text x="6" y="223"><tspan font-weight="bold">12</tspan><tspan> GPIO21 / REV_OE_N</tspan></text><circle id="probe-d4-gpio21" cx="287" cy="219" r="7" fill="#7b1fa2" stroke="#111111" stroke-width="1.5"/>',
        '<rect id="p4-ext2-pin11" x="0" y="234" width="300" height="22" rx="3" fill="#fbc02d" stroke="#333333" stroke-width="1.5"/><text x="6" y="249" fill="#111111"><tspan font-weight="bold">11</tspan><tspan> GPIO22 / D0</tspan></text><circle id="probe-red-gpio22" cx="287" cy="245" r="7" fill="#d32f2f" stroke="#555555" stroke-width="1.5"/>':
        '<rect id="p4-ext2-pin11" x="0" y="234" width="300" height="22" rx="3" fill="#fbc02d" stroke="#333333" stroke-width="1.5"/><text x="6" y="249" fill="#111111"><tspan font-weight="bold">11</tspan><tspan> GPIO22 / UART RX / D0</tspan></text><circle id="probe-d2-gpio22" cx="287" cy="245" r="7" fill="#1976d2" stroke="#111111" stroke-width="1.5"/>',
        '<rect id="p4-ext2-pin10" x="0" y="260" width="300" height="22" rx="3" fill="#f57c00" stroke="#333333" stroke-width="1.5"/><text x="6" y="275" fill="#111111"><tspan font-weight="bold">10</tspan><tspan> GPIO23 / D2</tspan></text><circle id="probe-brown-gpio23" cx="287" cy="271" r="7" fill="#6d4c41" stroke="#555555" stroke-width="1.5"/>':
        '<rect id="p4-ext2-pin10" x="0" y="260" width="300" height="22" rx="3" fill="#f57c00" stroke="#333333" stroke-width="1.5"/><text x="6" y="275" fill="#111111"><tspan font-weight="bold">10</tspan><tspan> GPIO23 / D2</tspan></text>',
        '<rect id="p4-ext2-pin9" x="0" y="286" width="300" height="22" rx="3" fill="#d32f2f" stroke="#333333" stroke-width="1.5"/><text x="6" y="301" fill="#ffffff"><tspan font-weight="bold">9</tspan><tspan> GPIO32 / D4</tspan></text>':
        '<rect id="p4-ext2-pin9" x="0" y="286" width="300" height="22" rx="3" fill="#d32f2f" stroke="#333333" stroke-width="1.5"/><text x="6" y="301" fill="#ffffff"><tspan font-weight="bold">9</tspan><tspan> GPIO32 / D4</tspan></text><circle id="probe-d0-gpio32" cx="287" cy="297" r="7" fill="#388e3c" stroke="#111111" stroke-width="1.5"/>',
    }
    for old, new in ext2_rows.items():
        document = replace_once(document, old, new)

    route = '''    <g id="route-pd4">
      <polyline id="wire-pd4-underlay" points="190,238.8089 630,238.8089" stroke="#ffffff" stroke-width="9"/>
      <polyline id="wire-pd4" class="wire-conductor" data-net="PD4" points="190,238.8089 630,238.8089" stroke="#1976d2" stroke-width="3"/>
    </g>'''
    route_with_label = route + '''
    <g id="ready-normal-path-callout">
      <rect x="305" y="210.8089" width="270" height="20" rx="4" fill="#ffffff" stroke="#1976d2" stroke-width="1.5"/>
      <text x="440" y="224.8089" text-anchor="middle" font-size="11" font-weight="bold" fill="#0d47a1">READY_N · Agon PD4 → P4 GPIO20</text>
    </g>'''
    document = replace_once(document, route, route_with_label)

    legend = '''
  <g id="normal-forward-state-and-la03-legend">
    <rect x="-125" y="1225" width="1350" height="170" rx="10" fill="#f7f7f7" stroke="#333333" stroke-width="2"/>
    <text x="-100" y="1252" font-size="16" font-weight="bold" fill="#111111">Normal r01 forward wiring · canonical LA-03 probe placement</text>
    <g font-size="12" font-weight="bold" fill="#111111">
      <circle cx="-90" cy="1280" r="7" fill="#388e3c" stroke="#111111" stroke-width="1.5"/><text x="-75" y="1284">D0 · GPIO32 · parallel D4</text>
      <circle cx="205" cy="1280" r="7" fill="#fbc02d" stroke="#111111" stroke-width="1.5"/><text x="220" y="1284">D1 · GPIO12 · UART TX / D1</text>
      <circle cx="520" cy="1280" r="7" fill="#1976d2" stroke="#111111" stroke-width="1.5"/><text x="535" y="1284">D2 · GPIO22 · UART RX / D0</text>
      <circle cx="830" cy="1280" r="7" fill="#f57c00" stroke="#111111" stroke-width="1.5"/><text x="845" y="1284">D3 · GPIO13 · VALID_N</text>
      <circle cx="-90" cy="1310" r="7" fill="#7b1fa2" stroke="#111111" stroke-width="1.5"/><text x="-75" y="1314">D4 · GPIO21 · REV_OE_N</text>
      <circle cx="205" cy="1310" r="7" fill="#d32f2f" stroke="#111111" stroke-width="1.5"/><text x="220" y="1314">D5 · GPIO14 · CLOCK</text>
      <circle cx="520" cy="1310" r="7" fill="#808080" stroke="#111111" stroke-width="1.5"/><text x="535" y="1314">D6 · GPIO20 · READY_N</text>
      <circle cx="830" cy="1310" r="7" fill="#6d4c41" stroke="#111111" stroke-width="1.5"/><text x="845" y="1314">D7 · GPIO15 · FWD_OE_N</text>
    </g>
    <text x="-100" y="1347" font-size="13" font-weight="bold" fill="#111111">BLACK GND · retain the qualified P4 signal-ground attachment.</text>
    <text x="-100" y="1377" font-size="13" font-weight="bold" fill="#0d47a1">READY_N normal state · Agon PD4 → P4 EXT2 pin 13 / GPIO20 · alter wiring only while both boards are powered off.</text>
  </g>
'''
    document = replace_once(document, "</svg>", legend + "</svg>")

    OUTPUT.write_text(document, encoding="utf-8")
    print(OUTPUT.relative_to(REPOSITORY))


if __name__ == "__main__":
    main()
