#!/usr/bin/env python3
"""Generate the deterministic SETUP-003 Work 5 source symbol index."""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import subprocess


EXPECTED_RELEASE_TAG = "v2.16.0"
EXPECTED_RELEASE_COMMIT = "c7ac293d2aa81ddfa693390549bcd909069c8fc3"
EXPECTED_VDP_GL_COMMIT = "ac2dd5986daf496c43ae8e7fe41836274aec54a0"
GENERATOR_VERSION = "1.0.0"

RETAINED_FIELDS = (
    "name",
    "path",
    "line",
    "end",
    "kind",
    "language",
    "scope",
    "scopeKind",
    "signature",
    "typeref",
    "file",
    "access",
    "implementation",
    "properties",
    "macrodef",
)


def scalar(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)


def source_identity(path: str) -> tuple[str, str]:
    prefixes = (
        ("video/", "agon-vdp", "video/"),
        (".pio/libdeps/p4-work3/vdp-gl/", "vdp-gl", ""),
        (".pio/libdeps/p4-work3/ESP32Time/", "ESP32Time", ""),
        (".pio/libdeps/p4-work3/CRC/", "CRC", ""),
    )
    for prefix, owner, replacement in prefixes:
        if path.startswith(prefix):
            suffix = path[len(prefix) :]
            return owner, replacement + suffix
    raise ValueError(f"unclassified ctags path: {path}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--ctags", required=True, type=Path)
    parser.add_argument("--output", type=Path, default=Path("docs/tasks/SETUP-003/generated/symbols.yaml"))
    args = parser.parse_args()
    source = args.source.resolve()
    ctags = args.ctags.resolve()
    output = args.output.resolve()

    commit = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=source, text=True, capture_output=True, check=True
    ).stdout.strip()
    if commit != EXPECTED_RELEASE_COMMIT:
        parser.error(f"source is {commit}, expected {EXPECTED_RELEASE_COMMIT}")
    vdp_gl = source / ".pio/libdeps/p4-work3/vdp-gl"
    vdp_gl_commit = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=vdp_gl, text=True, capture_output=True, check=True
    ).stdout.strip()
    if vdp_gl_commit != EXPECTED_VDP_GL_COMMIT:
        parser.error(f"vdp-gl is {vdp_gl_commit}, expected {EXPECTED_VDP_GL_COMMIT}")

    version = subprocess.run(
        [str(ctags), "--version"], text=True, capture_output=True, check=True
    ).stdout.splitlines()[0]
    command = [
        str(ctags),
        "--output-format=json",
        "--fields=+nKSEafimr",
        "--fields-C++=+{properties}{macrodef}",
        "--kinds-C++=+px",
        "--languages=C,C++",
        "--map-C++=+.ino",
        "--sort=no",
        "-R",
        "-f",
        "-",
        "video",
        ".pio/libdeps/p4-work3/vdp-gl/src",
        ".pio/libdeps/p4-work3/ESP32Time/ESP32Time.cpp",
        ".pio/libdeps/p4-work3/ESP32Time/ESP32Time.h",
        ".pio/libdeps/p4-work3/CRC/src",
    ]
    result = subprocess.run(command, cwd=source, text=True, capture_output=True, check=True)
    records: list[dict[str, object]] = []
    for line in result.stdout.splitlines():
        tag = json.loads(line)
        if tag.get("_type") != "tag":
            continue
        owner, path = source_identity(tag["path"])
        record = {key: tag[key] for key in RETAINED_FIELDS if key in tag}
        record["owner"] = owner
        record["path"] = path
        record["role"] = "declaration" if tag["kind"] in {"prototype", "externvar"} else "definition"
        records.append(record)
    records.sort(
        key=lambda item: (
            str(item["owner"]), str(item["path"]), int(item.get("line", 0)),
            str(item["kind"]), str(item["name"]),
        )
    )
    by_owner = Counter(str(record["owner"]) for record in records)
    by_kind = Counter(str(record["kind"]) for record in records)

    lines = [
        "# Generated by docs/tasks/SETUP-003/scripts/generate-symbol-index.py; do not hand-edit.",
        "schema_version: 1",
        "generator:",
        "  name: generate-symbol-index",
        f"  version: {scalar(GENERATOR_VERSION)}",
        "  regeneration_command: >-",
        "    .venv/bin/python docs/tasks/SETUP-003/scripts/generate-symbol-index.py",
        "    --source <official-agon-vdp-checkout> --ctags <universal-ctags>",
        "source:",
        f"  release_tag: {scalar(EXPECTED_RELEASE_TAG)}",
        f"  commit: {scalar(commit)}",
        f"  vdp_gl_commit: {scalar(vdp_gl_commit)}",
        "  ESP32Time_version: \"2.0.6\"",
        "  CRC_version: \"1.0.4\"",
        f"tool: {scalar(version)}",
        "scope:",
        "  - agon-vdp/video",
        "  - vdp-gl/src",
        "  - ESP32Time library source",
        "  - CRC/src",
        f"total_symbols: {len(records)}",
        "counts_by_owner:",
    ]
    lines.extend(f"  {key}: {by_owner[key]}" for key in sorted(by_owner))
    lines.append("counts_by_kind:")
    lines.extend(f"  {key}: {by_kind[key]}" for key in sorted(by_kind))
    lines.append("symbols:")
    ordered_fields = ("owner", *RETAINED_FIELDS, "role")
    for record in records:
        first = True
        for key in ordered_fields:
            if key not in record:
                continue
            prefix = "  - " if first else "    "
            lines.append(f"{prefix}{key}: {scalar(record[key])}")
            first = False
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
