#!/usr/bin/env python3
"""PORT-008 preliminary compile-output/final-symbol similarity checker.

For each listed compiler-driver translation unit, this checker verifies the
target compile record, replays that compile without a shell, verifies the
resulting object (or exact archive member), and compares selected records from
two final target images.  It does not prove that either final image consumed the
listed object, that Git commit/cleanliness attestations are true, or that the
manifest-selected target and tools are authoritative.  It therefore never
reports D002 target-object consumption equivalence.

SECURITY: validation executes tools and compiler arguments selected by the
manifest.  Shell parsing is avoided, but this is not a sandbox: compiler flags
can load code or create additional outputs.  Use only trusted, locally reviewed
manifests, tools, source trees, and compile databases in an isolated build
environment.  No manifest is generated by this program.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import platform
import re
import shlex
import subprocess
import sys
import tempfile
from typing import Any, Iterable

from jsonschema import Draft202012Validator


TASK_ROOT = Path(__file__).resolve().parents[1]
SCHEMA = TASK_ROOT / "schema/target-object-equivalence-v1.schema.json"
ROLES = ("qualification", "release")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
AR_MAGIC = b"!<arch>\n"
THIN_AR_MAGIC = b"!<thin>\n"
AR_HEADER_SIZE = 60
DISASSEMBLY_HEADER = re.compile(
    r"^\s*([0-9a-fA-F]+)\s+<([^>]+)>:\s*$"
)
DISASSEMBLY_LINE = re.compile(r"^\s*([0-9a-fA-F]+):\s*(\S.*?)\s*$")
ARCHITECTURE_LINE = re.compile(r"architecture:\s*([^,\r\n]+)")
SHELL_OPERATORS = {"|", "||", "&", "&&", ";", "<", ">", ">>", "2>", "2>>"}
SIDE_OUTPUT_OPTIONS = ("-MF", "-MJ")
FORBIDDEN_REPLAY_OPTIONS = (
    "-save-temps",
    "--save-temps",
    "-fprofile-generate",
    "-fprofile-use",
    "--coverage",
)
DIRECT_ASSEMBLER_NAME = re.compile(r"(?:^|-)as(?:\.exe)?$")
MISSING_CLAIMS = (
    "link-contribution-from-supplied-object-or-archive-member",
    "git-cleanliness-and-commit-provenance",
    "target-and-tool-authority",
)
ASSEMBLER_SIDE_OUTPUT = re.compile(
    r"^-Wa,(?:-[al](?:[cdghlmns]*)?=|--MD(?:=|,)|--listing[^,]*=)"
)


class GateError(ValueError):
    """One fail-closed evidence condition was not met."""


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def canonical_bytes(value: Any) -> bytes:
    return (
        json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
        + "\n"
    ).encode("utf-8")


def canonical_sha256(value: Any) -> str:
    return sha256_bytes(canonical_bytes(value))


def normalize_text_bytes(value: bytes) -> str:
    text = value.decode("utf-8", errors="strict")
    lines = [line.rstrip() for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + ("\n" if lines else "")


def command_output_record(completed: subprocess.CompletedProcess[bytes]) -> dict[str, str]:
    return {
        "stdout": normalize_text_bytes(completed.stdout),
        "stderr": normalize_text_bytes(completed.stderr),
    }


def run_checked(argv: list[str], *, cwd: Path | None = None, timeout: int = 30) -> subprocess.CompletedProcess[bytes]:
    environment = os.environ.copy()
    environment["LC_ALL"] = "C"
    environment["LANG"] = "C"
    try:
        completed = subprocess.run(
            argv,
            cwd=cwd,
            env=environment,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise GateError(f"command failed to run: {shlex.join(argv)}: {exc}") from exc
    if completed.returncode != 0:
        stderr = completed.stderr.decode("utf-8", errors="replace").strip()
        raise GateError(
            f"command exited {completed.returncode}: {shlex.join(argv)}"
            + (f": {stderr}" if stderr else "")
        )
    return completed


def load_json(path: Path, label: str) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise GateError(f"{label} is not readable UTF-8 JSON: {path}: {exc}") from exc


def validate_schema(document: Any) -> None:
    schema = load_json(SCHEMA, "schema")
    Draft202012Validator.check_schema(schema)
    errors = sorted(
        Draft202012Validator(schema).iter_errors(document),
        key=lambda item: tuple(str(part) for part in item.absolute_path),
    )
    if errors:
        error = errors[0]
        location = "/".join(str(part) for part in error.absolute_path) or "<root>"
        raise GateError(f"manifest schema error at {location}: {error.message}")


def reject_declared_unsupported_producers(document: Any) -> None:
    """Give an actionable error before the schema's compiler-driver const."""
    if not isinstance(document, dict):
        return
    units = document.get("production_units")
    if not isinstance(units, list):
        return
    for unit in units:
        if not isinstance(unit, dict):
            continue
        unit_id = unit.get("id", "<unknown-unit>")
        builds = unit.get("builds")
        if not isinstance(builds, dict):
            continue
        for role in ROLES:
            record = builds.get(role)
            if not isinstance(record, dict):
                continue
            producer_kind = record.get("producer_kind")
            if producer_kind is not None and producer_kind != "compiler-driver":
                raise GateError(
                    f"{unit_id} {role} declares unsupported producer_kind "
                    f"{producer_kind!r}; preliminary schema v1 supports "
                    "compiler-driver commands only and cannot validate direct "
                    "assembler objects"
                )


def safe_path(root: Path, relative: str, label: str, *, require_file: bool = True) -> Path:
    pure = PurePosixPath(relative)
    if pure.is_absolute() or not pure.parts or any(part in ("", ".", "..") for part in pure.parts):
        raise GateError(f"{label} must be a normalized relative POSIX path: {relative!r}")
    if "\\" in relative:
        raise GateError(f"{label} must not contain a backslash: {relative!r}")
    root = root.resolve(strict=True)
    candidate = root.joinpath(*pure.parts)
    probe = root
    for part in pure.parts:
        probe = probe / part
        if probe.is_symlink():
            raise GateError(f"{label} traverses a symlink: {relative}")
    try:
        resolved = candidate.resolve(strict=True)
        resolved.relative_to(root)
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        raise GateError(f"{label} is missing or escapes its evidence root: {relative}") from exc
    if require_file and not resolved.is_file():
        raise GateError(f"{label} is not a regular file: {relative}")
    if not require_file and not resolved.is_dir():
        raise GateError(f"{label} is not a directory: {relative}")
    return resolved


def require_digest(path: Path, expected: str, label: str) -> None:
    actual = sha256_file(path)
    if actual != expected:
        raise GateError(f"{label} SHA-256 mismatch: expected {expected}, observed {actual}")


def require_recorded_digest(value: Any, expected: str, label: str) -> None:
    actual = canonical_sha256(value)
    if actual != expected:
        raise GateError(f"{label} digest mismatch: expected {expected}, observed {actual}")


def resolve_command_path(value: str, directory: Path) -> Path:
    candidate = Path(value)
    if not candidate.is_absolute():
        candidate = directory / candidate
    try:
        resolved = candidate.resolve(strict=True)
    except (FileNotFoundError, RuntimeError) as exc:
        raise GateError(f"command path does not exist: {value}") from exc
    if not resolved.is_file():
        raise GateError(f"command path is not a regular file: {value}")
    return resolved


def verify_tool(path: Path, record: dict[str, Any], label: str) -> Path:
    resolved = path.resolve(strict=True)
    if not resolved.is_file():
        raise GateError(f"{label} is not a regular file: {path}")
    if path.name != record["name"]:
        raise GateError(
            f"{label} name mismatch: manifest records {record['name']!r}, supplied {path.name!r}"
        )
    require_digest(resolved, record["executable_sha256"], f"{label} executable")
    version = run_checked([str(resolved), "--version"])
    require_recorded_digest(
        command_output_record(version), record["version_output_sha256"], f"{label} version output"
    )
    return resolved


def host_target_aliases() -> set[str]:
    machine = platform.machine().lower().replace("_", "-")
    aliases = {machine}
    if machine in {"x86-64", "amd64"}:
        aliases.update({"x86-64", "x86_64", "amd64", "i386:x86-64"})
    elif machine in {"aarch64", "arm64"}:
        aliases.update({"aarch64", "arm64"})
    return aliases


def reject_host_target(target: dict[str, Any]) -> None:
    triple = target["compiler_triple"].lower().replace("_", "-")
    architecture = target["object_architecture"].lower().replace("_", "-")
    for alias in host_target_aliases():
        normalized = alias.replace("_", "-")
        if triple.startswith(normalized) or architecture == normalized or normalized in architecture:
            raise GateError(
                "manifest describes the validation host architecture; host same-source "
                "evidence cannot satisfy the target-object gate"
            )


def parse_compile_arguments(record: dict[str, Any], label: str) -> list[str]:
    arguments = record.get("arguments")
    command = record.get("command")
    parsed_command: list[str] | None = None
    if command is not None:
        if not isinstance(command, str) or not command:
            raise GateError(f"{label} has an invalid command string")
        try:
            parsed_command = shlex.split(command, posix=True)
        except ValueError as exc:
            raise GateError(f"{label} command cannot be parsed safely: {exc}") from exc
    if arguments is not None:
        if (
            not isinstance(arguments, list)
            or not arguments
            or any(not isinstance(item, str) or not item or "\x00" in item for item in arguments)
        ):
            raise GateError(f"{label} arguments must be a nonempty string array")
        argv = list(arguments)
        if parsed_command is not None and parsed_command != argv:
            raise GateError(f"{label} command and arguments records disagree")
    elif parsed_command is not None:
        argv = parsed_command
    else:
        raise GateError(f"{label} lacks both arguments and command")
    if any(item in SHELL_OPERATORS for item in argv):
        raise GateError(f"{label} contains a shell operator; shell execution is forbidden")
    return argv


def record_path(value: str, directory: Path, root: Path, label: str) -> Path:
    candidate = Path(value)
    if not candidate.is_absolute():
        candidate = directory / candidate
    try:
        resolved = candidate.resolve(strict=True)
        resolved.relative_to(root)
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        raise GateError(f"{label} is missing or outside its evidence root: {value}") from exc
    return resolved


def load_compile_database(path: Path, label: str) -> list[dict[str, Any]]:
    document = load_json(path, label)
    if not isinstance(document, list) or not document:
        raise GateError(f"{label} must be a nonempty array")
    if any(not isinstance(item, dict) for item in document):
        raise GateError(f"{label} contains a non-object record")
    return document


def select_compile_record(
    records: list[dict[str, Any]], root: Path, source: Path, output: Path, label: str
) -> tuple[dict[str, Any], Path, list[str]]:
    matches: list[tuple[dict[str, Any], Path, list[str]]] = []
    for index, record in enumerate(records):
        if not all(isinstance(record.get(name), str) and record[name] for name in ("directory", "file", "output")):
            continue
        try:
            directory = record_path(record["directory"], root, root, f"{label}[{index}].directory")
            if not directory.is_dir():
                continue
            observed_source = record_path(record["file"], directory, root, f"{label}[{index}].file")
            observed_output = record_path(record["output"], directory, root, f"{label}[{index}].output")
        except GateError:
            continue
        if observed_source == source and observed_output == output:
            matches.append(
                (record, directory, parse_compile_arguments(record, f"{label}[{index}]"))
            )
    if len(matches) != 1:
        raise GateError(
            f"{label} must contain exactly one record for source {source} and output {output}; "
            f"observed {len(matches)}"
        )
    return matches[0]


def replace_roots(value: str, root: Path, build_root: Path) -> str:
    pairs = sorted(
        ((str(build_root), "${BUILD}"), (str(root), "${ROOT}")),
        key=lambda item: len(item[0]),
        reverse=True,
    )
    normalized = value
    for actual, replacement in pairs:
        normalized = normalized.replace(actual, replacement)
    return normalized


def expand_response_arguments(
    arguments: Iterable[str], *, directory: Path, root: Path, build_root: Path,
    stack: tuple[Path, ...] = (), depth: int = 0,
) -> tuple[list[Any], list[str], list[str]]:
    if depth > 5:
        raise GateError("compile command response-file nesting exceeds five levels")
    structured: list[Any] = []
    flat: list[str] = []
    replay_flat: list[str] = []
    for argument in arguments:
        if not argument.startswith("@"):
            normalized = replace_roots(argument, root, build_root)
            structured.append(normalized)
            flat.append(normalized)
            replay_flat.append(argument)
            continue
        raw_path = argument[1:]
        if not raw_path:
            raise GateError("compile command contains an empty response-file argument")
        response = record_path(raw_path, directory, root, "compiler response file")
        if response in stack:
            raise GateError(f"compiler response-file cycle at {response}")
        try:
            text = response.read_text(encoding="utf-8")
            nested = shlex.split(text, posix=True)
        except (OSError, UnicodeError, ValueError) as exc:
            raise GateError(f"cannot parse compiler response file {response}: {exc}") from exc
        nested_structured, nested_flat, nested_replay = expand_response_arguments(
            nested,
            directory=directory,
            root=root,
            build_root=build_root,
            stack=(*stack, response),
            depth=depth + 1,
        )
        structured.append(
            {
                "response_file": replace_roots(str(response), root, build_root),
                "sha256": sha256_file(response),
                "arguments": nested_structured,
            }
        )
        flat.extend(nested_flat)
        replay_flat.extend(nested_replay)
    return structured, flat, replay_flat


def output_option_indexes(argv: list[str], label: str) -> tuple[int, int | None]:
    found: list[tuple[int, int | None]] = []
    index = 1
    while index < len(argv):
        value = argv[index]
        if value == "-o":
            if index + 1 >= len(argv):
                raise GateError(f"{label} has a trailing -o")
            found.append((index, index + 1))
            index += 2
            continue
        if value.startswith("-o") and len(value) > 2:
            found.append((index, None))
        index += 1
    if len(found) != 1:
        raise GateError(f"{label} must have exactly one compiler output option; observed {len(found)}")
    return found[0]


def compiler_identity(
    compiler: Path, record: dict[str, Any], target: dict[str, Any], label: str
) -> dict[str, str]:
    if compiler.name != record["name"]:
        raise GateError(
            f"{label} compiler name mismatch: manifest records {record['name']!r}, "
            f"compile command uses {compiler.name!r}"
        )
    require_digest(compiler, record["executable_sha256"], f"{label} compiler executable")
    version = run_checked([str(compiler), "--version"])
    require_recorded_digest(
        command_output_record(version), record["version_output_sha256"], f"{label} compiler version"
    )
    machine = run_checked([str(compiler), "-dumpmachine"])
    target_output = normalize_text_bytes(machine.stdout).strip()
    if target_output != target["compiler_triple"]:
        raise GateError(
            f"{label} compiler target mismatch: expected {target['compiler_triple']!r}, "
            f"observed {target_output!r}"
        )
    return {
        "name": compiler.name,
        "executable_sha256": sha256_file(compiler),
        "version_output_sha256": canonical_sha256(command_output_record(version)),
        "compiler_triple": target_output,
    }


def definitions_and_flags(arguments: list[str]) -> tuple[list[str], list[str]]:
    definitions: list[str] = []
    flags: list[str] = []
    index = 1
    while index < len(arguments):
        value = arguments[index]
        if value in ("-D", "-U"):
            if index + 1 >= len(arguments):
                raise GateError(f"compile command has trailing {value}")
            definitions.append(value + arguments[index + 1])
            index += 2
            continue
        if (value.startswith("-D") or value.startswith("-U")) and len(value) > 2:
            definitions.append(value)
        else:
            flags.append(value)
        index += 1
    return definitions, flags


def normalize_compile_record(
    argv: list[str], *, directory: Path, root: Path, build_root: Path,
    source: Path, output: Path, label: str,
) -> tuple[dict[str, Any], list[str], list[str], Path, list[str]]:
    producer_name = Path(argv[0]).name
    if DIRECT_ASSEMBLER_NAME.search(producer_name):
        raise GateError(
            f"{label} uses unsupported direct assembler producer {producer_name!r}; "
            "preliminary schema v1 supports compiler-driver commands only"
        )
    if "-c" not in argv:
        raise GateError(
            f"{label} is not a supported compiler-driver compile command: "
            "the required -c option is absent; direct assembler producers are unsupported"
        )
    compiler = resolve_command_path(argv[0], directory)
    output_index, output_value_index = output_option_indexes(argv, label)
    source_positions = []
    for index, argument in enumerate(argv[1:], start=1):
        if argument.startswith("-") or argument.startswith("@"):
            continue
        try:
            candidate = record_path(argument, directory, root, f"{label} source candidate")
        except GateError:
            continue
        if candidate == source:
            source_positions.append(index)
    if len(source_positions) != 1:
        raise GateError(f"{label} must name its source exactly once; observed {len(source_positions)}")

    rewritten = list(argv)
    rewritten[0] = "${COMPILER}"
    rewritten[source_positions[0]] = "${SOURCE}"
    if output_value_index is not None:
        rewritten[output_value_index] = "${OUTPUT}"
    else:
        rewritten[output_index] = "-o${OUTPUT}"
    structured, flat, _ = expand_response_arguments(
        rewritten, directory=directory, root=root, build_root=build_root
    )
    _, _, replay_arguments = expand_response_arguments(
        argv, directory=directory, root=root, build_root=build_root
    )
    output_option_indexes(replay_arguments, label)
    if any(argument.startswith(FORBIDDEN_REPLAY_OPTIONS) for argument in replay_arguments):
        raise GateError(f"{label} contains a side-effecting replay option")
    if any(ASSEMBLER_SIDE_OUTPUT.match(argument) for argument in replay_arguments):
        raise GateError(f"{label} contains an assembler side-output option")
    normalized_directory = replace_roots(str(directory), root, build_root)
    command_record = {"directory": normalized_directory, "arguments": structured}
    definitions, flags = definitions_and_flags(flat)
    return command_record, definitions, flags, compiler, replay_arguments


def replay_compile(
    argv: list[str], *, compiler: Path, directory: Path, expected: Path,
    timeout: int, label: str,
) -> str:
    output_index, output_value_index = output_option_indexes(argv, label)
    with tempfile.TemporaryDirectory(prefix="port008-object-replay-") as temporary:
        temporary_root = Path(temporary)
        replay_output = temporary_root / "replayed.o"
        replay = list(argv)
        replay[0] = str(compiler)
        if output_value_index is not None:
            replay[output_value_index] = str(replay_output)
        else:
            replay[output_index] = "-o" + str(replay_output)
        index = 1
        while index < len(replay):
            value = replay[index]
            if value in SIDE_OUTPUT_OPTIONS:
                if index + 1 >= len(replay):
                    raise GateError(f"{label} has a trailing {value}")
                replay[index + 1] = str(temporary_root / f"side-{index}")
                index += 2
                continue
            replaced = False
            for option in SIDE_OUTPUT_OPTIONS:
                if value.startswith(option) and len(value) > len(option):
                    replay[index] = option + str(temporary_root / f"side-{index}")
                    replaced = True
                    break
            for option in ("-Wp,-MD,", "-Wp,-MMD,"):
                if value.startswith(option):
                    replay[index] = option + str(temporary_root / f"side-{index}")
                    replaced = True
                    break
            index += 1
            if replaced:
                continue
        run_checked(replay, cwd=directory, timeout=timeout)
        if not replay_output.is_file():
            raise GateError(f"{label} replay did not produce its requested object")
        replay_digest = sha256_file(replay_output)
    expected_digest = sha256_file(expected)
    if replay_digest != expected_digest:
        raise GateError(
            f"{label} replay object differs from recorded compile output: "
            f"expected {expected_digest}, observed {replay_digest}"
        )
    return replay_digest


def archive_member(data: bytes, requested: str, label: str) -> bytes:
    if data.startswith(THIN_AR_MAGIC):
        raise GateError(f"{label} is a thin archive; external-member archives are unsupported")
    if not data.startswith(AR_MAGIC):
        raise GateError(f"{label} is not a System V/GNU/BSD ar archive")
    offset = len(AR_MAGIC)
    raw_records: list[tuple[str, bytes]] = []
    string_table: bytes | None = None
    while offset < len(data):
        if len(data) - offset < AR_HEADER_SIZE:
            raise GateError(f"{label} has a truncated member header")
        header = data[offset : offset + AR_HEADER_SIZE]
        offset += AR_HEADER_SIZE
        if header[58:60] != b"`\n":
            raise GateError(f"{label} has an invalid member trailer")
        raw_name = header[0:16].decode("ascii", errors="strict").rstrip()
        try:
            size = int(header[48:58].decode("ascii", errors="strict").strip(), 10)
        except (UnicodeError, ValueError) as exc:
            raise GateError(f"{label} has an invalid member size") from exc
        if size < 0 or offset + size > len(data):
            raise GateError(f"{label} has a truncated member payload")
        payload = data[offset : offset + size]
        offset += size
        if offset & 1:
            if offset >= len(data):
                raise GateError(f"{label} lacks required archive padding")
            offset += 1
        if raw_name == "//":
            string_table = payload
        else:
            raw_records.append((raw_name, payload))
    if offset != len(data):
        raise GateError(f"{label} has trailing malformed bytes")

    matches: list[bytes] = []
    for raw_name, raw_payload in raw_records:
        if raw_name in {"/", "/SYM64/"} or raw_name.startswith("__.SYMDEF"):
            continue
        payload = raw_payload
        if raw_name.startswith("#1/"):
            try:
                length = int(raw_name[3:], 10)
            except ValueError as exc:
                raise GateError(f"{label} has an invalid BSD extended name") from exc
            if length > len(payload):
                raise GateError(f"{label} has a truncated BSD extended name")
            name = payload[:length].decode("utf-8", errors="strict").rstrip("\x00")
            payload = payload[length:]
        elif raw_name.startswith("/") and raw_name[1:].isdigit():
            if string_table is None:
                raise GateError(f"{label} references a missing GNU string table")
            start = int(raw_name[1:], 10)
            if start >= len(string_table):
                raise GateError(f"{label} has an invalid GNU name offset")
            end_candidates = [
                value for value in (string_table.find(b"/\n", start), string_table.find(b"\x00", start))
                if value >= 0
            ]
            end = min(end_candidates) if end_candidates else len(string_table)
            name = string_table[start:end].decode("utf-8", errors="strict")
        else:
            name = raw_name[:-1] if raw_name.endswith("/") else raw_name
        if name == requested:
            matches.append(payload)
    if len(matches) != 1:
        raise GateError(
            f"{label} must contain exactly one member named {requested!r}; observed {len(matches)}"
        )
    return matches[0]


def verify_artifact(
    root: Path, compile_output: Path, record: dict[str, Any], label: str
) -> tuple[bytes, Path]:
    path = safe_path(root, record["path"], f"{label} artifact")
    require_digest(path, record["container_sha256"], f"{label} artifact container")
    if record["kind"] == "object":
        payload = path.read_bytes()
        if record["member"] is not None:
            raise GateError(f"{label} object artifact unexpectedly names a member")
    elif record["kind"] == "archive-member":
        payload = archive_member(path.read_bytes(), record["member"], label)
    else:  # The schema should make this unreachable.
        raise GateError(f"{label} has unsupported artifact kind {record['kind']!r}")
    payload_digest = sha256_bytes(payload)
    if payload_digest != record["payload_sha256"]:
        raise GateError(
            f"{label} artifact payload SHA-256 mismatch: expected {record['payload_sha256']}, "
            f"observed {payload_digest}"
        )
    output_digest = sha256_file(compile_output)
    if output_digest != payload_digest:
        raise GateError(
            f"{label} linked artifact payload does not equal its compile output: "
            f"{payload_digest} != {output_digest}"
        )
    return payload, path


def file_architecture(objdump: Path, path: Path, expected: str, label: str) -> str:
    completed = run_checked([str(objdump), "-f", str(path)])
    output = normalize_text_bytes(completed.stdout)
    match = ARCHITECTURE_LINE.search(output)
    if match is None:
        raise GateError(f"{label} objdump output has no architecture record")
    observed = match.group(1).strip()
    if observed != expected:
        raise GateError(
            f"{label} architecture mismatch: expected {expected!r}, observed {observed!r}"
        )
    return observed


def linked_symbol_table(nm: Path, image: Path, label: str) -> dict[str, list[dict[str, Any]]]:
    completed = run_checked(
        [str(nm), "-P", "--defined-only", "--print-size", str(image)]
    )
    records: dict[str, list[dict[str, Any]]] = {}
    for line in normalize_text_bytes(completed.stdout).splitlines():
        fields = line.split()
        if len(fields) < 4:
            continue
        name, symbol_type, value, size = fields[:4]
        if len(symbol_type) != 1:
            raise GateError(f"{label} has malformed nm type for {name!r}")
        try:
            int(value, 16)
            parsed_size = int(size, 16)
        except ValueError as exc:
            raise GateError(f"{label} has malformed nm address/size for {name!r}") from exc
        records.setdefault(name, []).append(
            {"name": name, "type": symbol_type, "size": parsed_size}
        )
    if not records:
        raise GateError(f"{label} nm output contains no sized defined symbols")
    return records


def select_linked_symbol_records(
    table: dict[str, list[dict[str, Any]]], names: list[str], label: str
) -> list[dict[str, Any]]:
    missing_or_duplicate = {
        name: len(table.get(name, []))
        for name in names
        if len(table.get(name, [])) != 1
    }
    if missing_or_duplicate:
        raise GateError(f"{label} linked symbols are missing or ambiguous: {missing_or_duplicate}")
    return [table[name][0] for name in sorted(names)]


def normalize_instruction(text: str) -> str:
    normalized = " ".join(text.split())
    normalized = re.sub(
        r"(?<![A-Za-z0-9_])(?:0x)?[0-9a-fA-F]+\s*<([^>]+)>", r"<\1>", normalized
    )
    return normalized


def normalized_disassembly(
    objdump: Path, image: Path, symbols: list[str], label: str, *, relocations: bool
) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for symbol in sorted(symbols):
        argv = [str(objdump), "-d"]
        if relocations:
            argv.append("-r")
        argv.extend(["--no-show-raw-insn", f"--disassemble={symbol}", str(image)])
        completed = run_checked(argv)
        lines = normalize_text_bytes(completed.stdout).splitlines()
        start: int | None = None
        instructions: list[dict[str, Any]] = []
        for line in lines:
            header = DISASSEMBLY_HEADER.match(line)
            if header is not None:
                if header.group(2) == symbol:
                    start = int(header.group(1), 16)
                    continue
                if start is not None:
                    break
            if start is None:
                continue
            instruction = DISASSEMBLY_LINE.match(line)
            if instruction is None:
                continue
            address = int(instruction.group(1), 16)
            if address < start:
                raise GateError(f"{label} disassembly address precedes {symbol!r}")
            instructions.append(
                {
                    "offset": address - start,
                    "text": normalize_instruction(instruction.group(2)),
                }
            )
        if start is None or not instructions:
            raise GateError(f"{label} has no disassembly record for {symbol!r}")
        result.append({"symbol": symbol, "instructions": instructions})
    return result


def unique_values(values: Iterable[str], label: str) -> None:
    observed = list(values)
    duplicates = sorted({value for value in observed if observed.count(value) > 1})
    if duplicates:
        raise GateError(f"{label} contains duplicate values: {duplicates}")


def compare_equal(left: Any, right: Any, label: str) -> None:
    if left != right:
        raise GateError(f"qualification/release {label} differ")


def inspect_unit_build(
    *, role: str, unit: dict[str, Any], unit_record: dict[str, Any], root: Path,
    build_root: Path, compile_records: list[dict[str, Any]], linked_image: Path,
    target: dict[str, Any], linked_symbols: dict[str, list[dict[str, Any]]],
    objdump: Path, replay_timeout: int,
) -> dict[str, Any]:
    label = f"{unit['id']} {role}"
    source_record = unit_record["source"]
    output_record = unit_record["compile_output"]
    source = safe_path(root, source_record["path"], f"{label} source")
    compile_output = safe_path(root, output_record["path"], f"{label} compile output")
    try:
        compile_output.relative_to(build_root)
    except ValueError as exc:
        raise GateError(f"{label} compile output is outside its declared build root") from exc
    require_digest(source, source_record["sha256"], f"{label} source")
    require_digest(compile_output, output_record["sha256"], f"{label} compile output")
    _, directory, argv = select_compile_record(
        compile_records, root, source, compile_output, f"{role} compile database"
    )
    command_record, definitions, flags, compiler, replay_arguments = normalize_compile_record(
        argv,
        directory=directory,
        root=root,
        build_root=build_root,
        source=source,
        output=compile_output,
        label=label,
    )
    require_recorded_digest(
        command_record,
        unit_record["normalized_compile_command_sha256"],
        f"{label} normalized compile command",
    )
    require_recorded_digest(
        definitions, unit_record["normalized_defines_sha256"], f"{label} normalized defines"
    )
    require_recorded_digest(
        flags, unit_record["normalized_flags_sha256"], f"{label} normalized flags"
    )
    compiler_record = compiler_identity(
        compiler, unit_record["compiler"], target, label
    )
    replay_digest = replay_compile(
        replay_arguments,
        compiler=compiler,
        directory=directory,
        expected=compile_output,
        timeout=replay_timeout,
        label=label,
    )
    payload, _ = verify_artifact(root, compile_output, unit_record["artifact"], label)
    with tempfile.TemporaryDirectory(prefix="port008-object-inspect-") as temporary:
        payload_path = Path(temporary) / "claimed-production.o"
        payload_path.write_bytes(payload)
        payload_architecture = file_architecture(
            objdump, payload_path, target["object_architecture"], f"{label} object"
        )
        object_symbols = [record["object_name"] for record in unit["symbols"]]
        object_disassembly = normalized_disassembly(
            objdump,
            payload_path,
            object_symbols,
            f"{label} object",
            relocations=True,
        )
    linked_names = [record["linked_name"] for record in unit["symbols"]]
    symbol_records = select_linked_symbol_records(linked_symbols, linked_names, label)
    linked_disassembly = normalized_disassembly(
        objdump,
        linked_image,
        linked_names,
        f"{label} linked image",
        relocations=False,
    )
    require_recorded_digest(
        symbol_records,
        unit_record["linked_symbol_records_sha256"],
        f"{label} linked symbol records",
    )
    require_recorded_digest(
        linked_disassembly,
        unit_record["normalized_linked_disassembly_sha256"],
        f"{label} normalized linked disassembly",
    )
    require_recorded_digest(
        object_disassembly,
        unit_record["normalized_object_disassembly_sha256"],
        f"{label} normalized object disassembly",
    )
    return {
        "source_path": source_record["path"],
        "source_sha256": source_record["sha256"],
        "command": command_record,
        "definitions": definitions,
        "flags": flags,
        "compiler": compiler_record,
        "compile_output_sha256": output_record["sha256"],
        "replay_sha256": replay_digest,
        "artifact_kind": unit_record["artifact"]["kind"],
        "artifact_member": unit_record["artifact"]["member"],
        "payload_sha256": unit_record["artifact"]["payload_sha256"],
        "object_architecture": payload_architecture,
        "symbol_records": symbol_records,
        "linked_disassembly": linked_disassembly,
        "object_disassembly": object_disassembly,
    }


def validate(
    manifest_path: Path, qualification_root: Path, release_root: Path,
    nm_path: Path, objdump_path: Path, *, replay_timeout: int = 120,
) -> dict[str, Any]:
    manifest_path = manifest_path.resolve(strict=True)
    document = load_json(manifest_path, "manifest")
    reject_declared_unsupported_producers(document)
    validate_schema(document)
    target = document["target"]
    reject_host_target(target)
    roots = {
        "qualification": qualification_root.resolve(strict=True),
        "release": release_root.resolve(strict=True),
    }
    if any(not root.is_dir() for root in roots.values()):
        raise GateError("qualification and release evidence roots must be directories")

    nm = verify_tool(nm_path, document["inspection_tools"]["nm"], "nm")
    objdump = verify_tool(
        objdump_path, document["inspection_tools"]["objdump"], "objdump"
    )
    build_state: dict[str, dict[str, Any]] = {}
    for role in ROLES:
        record = document["builds"][role]
        root = roots[role]
        build_root = safe_path(root, record["build_root"], f"{role} build root", require_file=False)
        compile_database = safe_path(
            root, record["compile_database"]["path"], f"{role} compile database"
        )
        linked_image = safe_path(
            root, record["linked_image"]["path"], f"{role} linked image"
        )
        try:
            compile_database.relative_to(build_root)
            linked_image.relative_to(build_root)
        except ValueError as exc:
            raise GateError(
                f"{role} compile database and linked image must be inside its build root"
            ) from exc
        require_digest(
            compile_database,
            record["compile_database"]["sha256"],
            f"{role} compile database",
        )
        require_digest(
            linked_image, record["linked_image"]["sha256"], f"{role} linked image"
        )
        image_architecture = file_architecture(
            objdump, linked_image, target["object_architecture"], f"{role} linked image"
        )
        build_state[role] = {
            "root": root,
            "build_root": build_root,
            "compile_records": load_compile_database(
                compile_database, f"{role} compile database"
            ),
            "linked_image": linked_image,
            "linked_symbols": linked_symbol_table(
                nm, linked_image, f"{role} linked image"
            ),
            "image_architecture": image_architecture,
        }

    qualification_build = document["builds"]["qualification"]
    release_build = document["builds"]["release"]
    if qualification_build["build_id"] == release_build["build_id"]:
        raise GateError("qualification and release build IDs must be distinct")
    if build_state["qualification"]["build_root"] == build_state["release"]["build_root"]:
        raise GateError("qualification and release must use distinct build roots")
    if build_state["qualification"]["linked_image"] == build_state["release"]["linked_image"]:
        raise GateError("qualification and release must use distinct linked-image files")
    if (
        qualification_build["linked_image"]["sha256"]
        == release_build["linked_image"]["sha256"]
    ):
        raise GateError(
            "qualification-only and production-release linked images are byte-identical; "
            "the composition boundary is not evidenced"
        )
    unit_ids = [unit["id"] for unit in document["production_units"]]
    unique_values(unit_ids, "production unit IDs")
    unit_reports = []
    for unit in sorted(document["production_units"], key=lambda item: item["id"]):
        unique_values(
            (record["object_name"] for record in unit["symbols"]),
            f"{unit['id']} object symbols",
        )
        unique_values(
            (record["linked_name"] for record in unit["symbols"]),
            f"{unit['id']} linked symbols",
        )
        observed = {}
        for role in ROLES:
            state = build_state[role]
            observed[role] = inspect_unit_build(
                role=role,
                unit=unit,
                unit_record=unit["builds"][role],
                root=state["root"],
                build_root=state["build_root"],
                compile_records=state["compile_records"],
                linked_image=state["linked_image"],
                target=target,
                linked_symbols=state["linked_symbols"],
                objdump=objdump,
                replay_timeout=replay_timeout,
            )
        for field, description in (
            ("source_path", "source paths"),
            ("source_sha256", "source digests"),
            ("definitions", "compiler defines"),
            ("flags", "compiler flags"),
            ("command", "normalized compile commands"),
            ("compiler", "compiler identities"),
            ("compile_output_sha256", "compile-output digests"),
            ("replay_sha256", "replayed-object digests"),
            ("artifact_kind", "artifact kinds"),
            ("artifact_member", "archive member names"),
            ("payload_sha256", "target-object payload digests"),
            ("object_architecture", "object architectures"),
            ("symbol_records", "linked symbol records"),
            ("linked_disassembly", "normalized linked disassembly records"),
            ("object_disassembly", "normalized object disassembly records"),
        ):
            compare_equal(
                observed["qualification"][field],
                observed["release"][field],
                f"{unit['id']} {description}",
            )
        unit_reports.append(
            {
                "id": unit["id"],
                "source_sha256": observed["qualification"]["source_sha256"],
                "supplied_artifact_payload_sha256": observed["qualification"][
                    "payload_sha256"
                ],
                "linked_symbol_records_sha256": canonical_sha256(
                    observed["qualification"]["symbol_records"]
                ),
                "normalized_linked_disassembly_sha256": canonical_sha256(
                    observed["qualification"]["linked_disassembly"]
                ),
                "normalized_object_disassembly_sha256": canonical_sha256(
                    observed["qualification"]["object_disassembly"]
                ),
            }
        )

    return {
        "schema_version": 1,
        "evidence_kind": "port-008-preliminary-object-similarity-check-result",
        "manifest_sha256": sha256_file(manifest_path),
        "evidence_class": "preliminary-compile-output-final-symbol-similarity",
        "input_trust_model": "caller-asserted-trusted-local-inputs",
        "manifest_declared_target": target,
        "qualification_build_id": qualification_build["build_id"],
        "release_build_id": release_build["build_id"],
        "manifest_attested_source_commits": {
            "qualification": qualification_build["source_commit"],
            "release": release_build["source_commit"],
        },
        "production_units": unit_reports,
        "claims": {
            "listed_compile_output_bytes_equal": True,
            "listed_artifact_payload_bytes_equal": True,
            "selected_final_symbol_records_similar": True,
            "selected_final_disassembly_similar": True,
            "link_contribution_proved": False,
            "git_cleanliness_and_commit_provenance_proved": False,
            "target_and_tool_authority_proved": False,
        },
        "missing_claims": list(MISSING_CLAIMS),
        "preliminary_checks_passed": True,
        "equivalence_proved": False,
    }


def write_report(path: Path, report: dict[str, Any]) -> None:
    if path.exists():
        raise GateError(f"refusing to overwrite preliminary similarity report: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(canonical_bytes(report))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--qualification-root", required=True, type=Path)
    parser.add_argument("--release-root", required=True, type=Path)
    parser.add_argument("--nm", required=True, type=Path)
    parser.add_argument("--objdump", required=True, type=Path)
    parser.add_argument("--replay-timeout", type=int, default=120)
    parser.add_argument("--report", type=Path)
    parser.add_argument(
        "--acknowledge-trusted-inputs",
        action="store_true",
        help=(
            "acknowledge that the manifest, tools, and compiler arguments are "
            "trusted local inputs and that this checker is not a sandbox"
        ),
    )
    args = parser.parse_args(argv)
    if args.replay_timeout < 1:
        parser.error("--replay-timeout must be positive")
    if not args.acknowledge_trusted_inputs:
        parser.error(
            "--acknowledge-trusted-inputs is required because validation executes "
            "manifest-selected programs and arguments"
        )
    try:
        report = validate(
            args.manifest,
            args.qualification_root,
            args.release_root,
            args.nm,
            args.objdump,
            replay_timeout=args.replay_timeout,
        )
        if args.report is not None:
            write_report(args.report, report)
        print(json.dumps(report, sort_keys=True))
        return 0
    except (GateError, FileNotFoundError, json.JSONDecodeError, UnicodeError) as exc:
        print(f"preliminary object-similarity checks failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
