# Optional P4 compatibility correction for ESP-DSP 1.8.0 (Apache-2.0),
# commit 196825deaa4848b2c8e87b6126491cd7fc87e5bf. Its determinant's zero-pivot
# return leaks the temporary matrix and data. Physical Rally traces and the
# matching host leak regression are recorded in PORT-003/video-throughput.
# Only add the missing delete; preserve all arithmetic and the managed source.
# Remove when the selected upstream dependency supplies equivalent cleanup.
# DSP_SOURCE/DSP_OUTPUT permit the same generator's standalone host regression.
if(NOT DEFINED DSP_SOURCE)
  idf_component_get_property(dsp_dir espressif__esp-dsp COMPONENT_DIR)
  idf_component_get_property(dsp_target espressif__esp-dsp COMPONENT_LIB)
  set(DSP_SOURCE "${dsp_dir}/modules/matrix/mat/mat.cpp")
  set(DSP_OUTPUT "${CMAKE_BINARY_DIR}/agon-extender-dsp/mat.cpp")
endif()
file(SHA256 "${DSP_SOURCE}" original_sha)
if(NOT original_sha STREQUAL "6dd88f0ff7e22769bbcc579fb8449693f7eaf4021bf723ee227ce34d5cb01864")
  message(FATAL_ERROR "Unreviewed ESP-DSP matrix source; lifetime patch refused")
endif()
file(READ "${DSP_SOURCE}" original)
set(before "        if ((*temp)(i, i) == 0) {\n            return 0;\n        }")
set(after "        if ((*temp)(i, i) == 0) {\n            // Extender: release ESP-DSP 1.8.0's temporary on this exit too.\n            // Source-bound recipe: pio/dsp_matrix_lifetime.cmake (PORT-003).\n            delete temp;\n            return 0;\n        }")
string(FIND "${original}" "${before}" position)
if(position LESS 0)
  message(FATAL_ERROR "Expected determinant exit is absent")
endif()
string(REPLACE "${before}" "${after}" patched "${original}")
get_filename_component(output_dir "${DSP_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${DSP_OUTPUT}" "${patched}")
file(SHA256 "${DSP_OUTPUT}" patched_sha)
message(STATUS "Extender DSP lifetime derivative SHA256 ${patched_sha}")

if(DEFINED dsp_target)
  get_target_property(dsp_sources "${dsp_target}" SOURCES)
  set(selected_sources)
  set(replacements 0)
  foreach(source IN LISTS dsp_sources)
    if(IS_ABSOLUTE "${source}")
      set(absolute_source "${source}")
    else()
      set(absolute_source "${dsp_dir}/${source}")
    endif()
    if(absolute_source STREQUAL DSP_SOURCE)
      list(APPEND selected_sources "${DSP_OUTPUT}")
      math(EXPR replacements "${replacements}+1")
    else()
      list(APPEND selected_sources "${source}")
    endif()
  endforeach()
  if(NOT replacements EQUAL 1)
    message(FATAL_ERROR "Expected exactly one selected DSP matrix translation unit")
  endif()
  set_property(TARGET "${dsp_target}" PROPERTY SOURCES "${selected_sources}")
endif()
