"""Select the exact application and vendored closure for an active P4 target.

PlatformIO's normal library discovery would compile vdp-gl's broad classic-
ESP32 implementation family. This recurring build hook instead consumes a
tracked, machine-readable allowlist and adds only the named translation units.
It deliberately does not infer a source closure or edit vendored code.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import re

Import("env")  # type: ignore[name-defined]  # Provided by PlatformIO/SCons.


environment = env.subst("$PIOENV")  # type: ignore[name-defined]
project_dir = Path(env.subst("$PROJECT_DIR"))  # type: ignore[name-defined]
environment_selection = project_dir / f"pio/{environment}-source-selection.json"
selection_path = (
    environment_selection
    if environment_selection.is_file()
    else project_dir / "pio/source-selection.json"
)
selection = json.loads(selection_path.read_text(encoding="utf-8"))
if environment != selection["environment"]:
    raise RuntimeError(
        f"{selection_path}: describes {selection['environment']}, not {environment}"
    )
if selection.get("retired") is True:
    raise RuntimeError(
        f"{selection_path}: source selection is rejected and superseded; "
        "it is retained only as historical inventory"
    )

project_translation_units = selection["project_translation_units"]
if len(project_translation_units) != len(set(project_translation_units)):
    raise RuntimeError(f"{selection_path}: duplicate project translation unit")
forbidden_translation_units = set(
    selection.get("forbidden_project_translation_units", [])
)
selected_forbidden = forbidden_translation_units.intersection(
    project_translation_units
)
if selected_forbidden:
    raise RuntimeError(
        f"{selection_path}: selects forbidden translation units: "
        + ", ".join(sorted(selected_forbidden))
    )

definition_pattern = re.compile(r"^[A-Z][A-Z0-9_]*(?:=[A-Za-z0-9_]+)?$")
component_compile_definitions = selection.get(
    "component_compile_definitions", []
)
for definition in component_compile_definitions:
    if not definition_pattern.fullmatch(definition):
        raise RuntimeError(
            f"{selection_path}: unsupported component definition {definition!r}"
        )

# Hybrid Arduino/ESP-IDF builds intentionally ignore PlatformIO's source
# filter and use the application component's CMake source list. Render that
# ignored generated boundary from the same allowlist so the two build systems
# cannot disagree about which project translation units enter the diagnostic.
component_sources = []
for relative in project_translation_units:
    source = project_dir / relative
    if not source.is_file():
        raise FileNotFoundError(source)
    # The retained component is rooted at video/, while explicitly vendored
    # single-file libraries such as ESP32Time remain under vendor/. Preserve
    # that ownership and render a reviewed relative CMake path rather than
    # copying the source into the official VDP-shaped tree.
    component_sources.append(
        Path(os.path.relpath(source, project_dir / "video")).as_posix()
    )

embedded_text_files = []
for relative in selection.get("embedded_text_files", []):
    source = project_dir / relative
    if not source.is_file():
        raise FileNotFoundError(source)
    embedded_text_files.append(source.relative_to(project_dir / "video").as_posix())

cmake_path = project_dir / selection["generated_build_files"][0]
cmake_text = """# Generated by pio/select_sources.py for an allowlisted P4 target.
# Hybrid Arduino/ESP-IDF ignores PlatformIO build_src_filter; do not hand-edit.
idf_component_register(
  SRCS
"""
cmake_text += "".join(f'    "${{CMAKE_CURRENT_LIST_DIR}}/{path}"\n' for path in component_sources)
if embedded_text_files:
    # PlatformIO's board_build.embed_txtfiles hook generates assembly but does
    # not link it into this pinned Arduino/ESP-IDF hybrid build. Registering the
    # same authoritative files with the application component uses ESP-IDF's
    # native mechanism and gives the linker one unambiguous owner.
    cmake_text += "  EMBED_TXTFILES\n"
    cmake_text += "".join(
        f'    "${{CMAKE_CURRENT_LIST_DIR}}/{path}"\n'
        for path in embedded_text_files
    )
cmake_text += ")\n"
# ESP-IDF 5.5 defaults C++ application components to gnu++2b and the hybrid
# CMake path does not inherit PlatformIO's build_flags. Extender-owned code is
# normatively C++17 (ADR-0011), so pin the generated application component at
# its actual compiler boundary. Without this line the visible platformio.ini
# setting is silently ineffective.
cmake_text += 'target_compile_options(${COMPONENT_LIB} PRIVATE "-std=gnu++17")\n'
if component_compile_definitions:
    cmake_text += "target_compile_definitions(${COMPONENT_LIB} PRIVATE\n"
    cmake_text += "".join(
        f"  {definition}\n" for definition in component_compile_definitions
    )
    cmake_text += ")\n"
cmake_path.write_text(cmake_text, encoding="utf-8", newline="\n")

vendored_root = project_dir / "vendor/vdp-gl/src"
selected_names = []
for relative in selection["vendored_translation_units"]:
    source = project_dir / relative
    if source.parent != vendored_root:
        raise RuntimeError(f"vendored source is outside the reviewed root: {source}")
    if not source.is_file():
        raise FileNotFoundError(source)
    selected_names.append(source.name)

env.BuildSources(  # type: ignore[name-defined]
    env.subst("$BUILD_DIR") + "/selected-vdp-gl",  # type: ignore[name-defined]
    str(vendored_root),
    src_filter=["-<*>", *(f"+<{name}>" for name in selected_names)],
)
