"""Select the exact vendored closure for the active PORT-003 diagnostic.

PlatformIO's normal library discovery would compile vdp-gl's broad classic-
ESP32 implementation family. This recurring build hook instead consumes a
tracked, machine-readable allowlist and adds only the named translation units.
It deliberately does not infer a source closure or edit vendored code.
"""

from __future__ import annotations

import json
from pathlib import Path

Import("env")  # type: ignore[name-defined]  # Provided by PlatformIO/SCons.


project_dir = Path(env.subst("$PROJECT_DIR"))  # type: ignore[name-defined]
selection_path = project_dir / "pio/source-selection.json"
selection = json.loads(selection_path.read_text(encoding="utf-8"))
environment = env.subst("$PIOENV")  # type: ignore[name-defined]
if environment != selection["environment"]:
    raise RuntimeError(
        f"{selection_path}: describes {selection['environment']}, not {environment}"
    )

# Hybrid Arduino/ESP-IDF builds intentionally ignore PlatformIO's source
# filter and use the application component's CMake source list. Render that
# ignored generated boundary from the same allowlist so the two build systems
# cannot disagree about which project translation units enter the diagnostic.
component_sources = []
for relative in selection["project_translation_units"]:
    source = project_dir / relative
    if not source.is_file():
        raise FileNotFoundError(source)
    component_sources.append(source.relative_to(project_dir / "video").as_posix())
cmake_path = project_dir / selection["generated_build_files"][0]
cmake_text = """# Generated by pio/select_sources.py for active PORT-003 work.
# Hybrid Arduino/ESP-IDF ignores PlatformIO build_src_filter; do not hand-edit.
idf_component_register(
  SRCS
"""
cmake_text += "".join(f'    "${{CMAKE_CURRENT_LIST_DIR}}/{path}"\n' for path in component_sources)
cmake_text += ")\n"
cmake_path.write_text(cmake_text, encoding="utf-8", newline="\n")

vendored_root = project_dir / "vendor/vdp-gl/src"
selected_names = []
for relative in selection["vendored_translation_units"]:
    source = project_dir / relative
    if source.parent != vendored_root:
        raise RuntimeError(f"vendored source is outside the reviewed root: {source}")
    if not source.is_file():
        raise FileNotFoundError(source)
    selected_names.append(source.name)

env.BuildSources(  # type: ignore[name-defined]
    env.subst("$BUILD_DIR") + "/selected-vdp-gl",  # type: ignore[name-defined]
    str(vendored_root),
    src_filter=["-<*>", *(f"+<{name}>" for name in selected_names)],
)
