#!/usr/bin/env python3
"""Render compact deterministic human views from the canonical matrix."""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from pathlib import Path

from qualification_model import GENERATED, load_yaml


HEADER = "<!-- Generated by docs/qualification/scripts/render-compatibility-views.py; do not hand-edit. -->\n"

CATEGORY_LABELS = {
    "base-vdu": "Base VDU commands",
    "direct-vdu-23": "Direct VDU 23 commands",
    "system": "System commands — VDU 23, 0",
    "mouse": "Mouse commands — VDU 23, 0, &89",
    "audio": "Audio commands — VDU 23, 0, &85",
    "bitmap-sprite": "Bitmap and sprite commands — VDU 23, 27",
    "font": "Font commands — VDU 23, 0, &95",
    "context": "Context commands — VDU 23, 0, &C8",
    "copper": "Copper commands — VDU 23, 0, &C4",
    "tile": "Tile commands — VDU 23, 0, &C2",
    "buffered": "Buffered commands — VDU 23, 0, &A0, bufferId;",
    "plot": "PLOT families — VDU 25, mode, x; y;",
}

DISPOSITION_SYMBOLS = {
    "supported": "✅",
    "accepted-noop": "🟡",
    "mode-dependent": "🔀",
    "unsupported": "⛔",
    "unresolved": "❓",
}


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + text.rstrip() + "\n", encoding="utf-8")


def _summary(matrix: dict) -> str:
    obligation_counts = Counter(item["qualification_state"] for item in matrix["obligations"])
    by_subject = defaultdict(list)
    for obligation in matrix["obligations"]:
        by_subject[obligation["subject_id"]].append(obligation)
    mode_lookup = {(item["interface_id"], item["mode_id"]): item for item in matrix["mode_expectations"]}
    mode_ids = [item["id"] for item in matrix["modes"]]
    lines = [
        "# Compatibility matrix",
        "",
        "Canonical data: [`compatibility-matrix.yaml`](compatibility-matrix.yaml).",
        "",
        f"Interfaces: **{len(matrix['interfaces'])}** · Obligations: **{len(matrix['obligations'])}** · "
        + " · ".join(f"{state}: **{count}**" for state, count in sorted(obligation_counts.items())),
        "",
        "| Interface | Disposition | Legacy | EDP-exclusive | Cooperative | Obligations |",
        "|---|---|---|---|---|---:|",
    ]
    mode_order = ["mode:extender:legacy", "mode:extender:edp-exclusive", "mode:extender:cooperative"]
    if set(mode_order) != set(mode_ids):
        mode_order = sorted(mode_ids)
    for interface in matrix["interfaces"]:
        expectations = [mode_lookup[(interface["id"], mode)]["expectation"] for mode in mode_order]
        lines.append(
            f"| `{interface['id']}` — {interface['selector']} — {interface['title']} | "
            f"{interface['disposition']} | {expectations[0]} | {expectations[1]} | {expectations[2]} | "
            f"{len(by_subject[interface['id']])} |"
        )
    return "\n".join(lines)


def _obligation_table(title: str, obligations: list[dict]) -> str:
    lines = [
        f"# {title}",
        "",
        "| Obligation | Subject | Kind | Owner | Implementation | Qualification | Blockers |",
        "|---|---|---|---|---|---|---|",
    ]
    for item in obligations:
        lines.append(
            f"| `{item['id']}` | `{item['subject_id']}` | {item['kind']} | "
            f"{', '.join(item['owner_task_ids']) or '—'} | {item['implementation_state']} | "
            f"{item['qualification_state']} | {', '.join(item['blocker_refs']) or '—'} |"
        )
    return "\n".join(lines)


def _vdu_inventory(matrix: dict) -> str:
    grouped = defaultdict(list)
    for interface in matrix["interfaces"]:
        grouped[interface["category"]].append(interface)
    lines = [
        "# VDU interface inventory",
        "",
        "Generated from the reviewed qualification interface records.",
        "",
        "Legend: ✅ supported · 🟡 accepted no-op · 🔀 retained, mode-dependent · "
        "⛔ unsupported by Extender v1 · ❓ unresolved",
    ]
    for category, label in CATEGORY_LABELS.items():
        lines.extend(["", f"## {label}", ""])
        for interface in sorted(grouped[category], key=lambda item: item["display_order"]):
            symbol = DISPOSITION_SYMBOLS[interface["disposition"]]
            lines.append(f"- {symbol} `{interface['selector']}` — {interface['title']}.")
    return "\n".join(lines)


def render(matrix: dict, output: Path) -> None:
    _write(output / "compatibility-matrix.md", _summary(matrix))
    _write(output / "vdu-inventory.md", _vdu_inventory(matrix))
    secondary = [item for item in matrix["obligations"] if item["scope"] == "secondary-capability"]
    _write(output / "secondary-capabilities.md", _obligation_table("Secondary capability qualification", secondary))
    compatibility = [item for item in matrix["obligations"] if item["scope"] == "compatibility-critical"]
    _write(output / "views" / "compatibility-obligations.md", _obligation_table("Compatibility-critical obligations", compatibility))
    blocked = [item for item in matrix["obligations"] if item["qualification_state"] == "blocked"]
    _write(output / "views" / "blocked-obligations.md", _obligation_table("Blocked qualification obligations", blocked))
    for mode in matrix["modes"]:
        selected = [item for item in matrix["obligations"] if mode["id"] in item["mode_ids"]]
        name = mode["id"].rsplit(":", 1)[-1]
        _write(output / "views" / f"mode-{name}.md", _obligation_table(f"Obligations for {mode['label']}", selected))
    task_map = defaultdict(list)
    for obligation in matrix["obligations"]:
        for task in obligation["owner_task_ids"]:
            task_map[task].append(obligation)
    for task, obligations in sorted(task_map.items()):
        _write(output / "views" / "tasks" / f"{task}.md", _obligation_table(f"Qualification owned by {task}", obligations))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("matrix", nargs="?", type=Path, default=GENERATED / "compatibility-matrix.yaml")
    parser.add_argument("--output", type=Path, default=GENERATED)
    args = parser.parse_args()
    render(load_yaml(args.matrix), args.output)
    print(f"rendered qualification views under {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
