#!/usr/bin/env python3
"""Build the independently SD-loaded C text sample; never edit physical media."""
import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import shutil
import subprocess
import yaml
from prepare_visible_text import ROOT, git, sha, snapshot, verify_embedded_identity


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--toolchain', type=Path,
                        default=ROOT.parent / 'mos-agondev/toolchains/agondev')
    args = parser.parse_args()
    output = args.output.absolute()
    output.mkdir(parents=True)  # A build never replaces an earlier bundle.
    identity = json.loads((ROOT / 'vdp/pio/p4-visible-text-identity.json').read_text())
    source_identity, status = identity['source_identity'], identity['status']
    before = {'commit': git('rev-parse', 'HEAD'), 'dirty': bool(git('status', '--porcelain')),
              'source_sha256': snapshot()}
    if status not in ('draft', 'candidate') or (status == 'candidate' and before['dirty']):
        raise SystemExit('Candidate sample requires clean committed inputs')
    now = datetime.now(timezone.utc)
    build_id = source_identity + now.strftime('-b%Y-%m-%d-%H-%M-%SZ')
    project = ROOT / 'tests/fixtures/visible-text'
    header = project / 'build/build_identity.h'
    header.parent.mkdir(exist_ok=True)
    header.write_text('// Generated by prepare_text_sample.py; do not edit.\n'
                      f'#define SAMPLE_ID "{source_identity}"\n'
                      f'#define SAMPLE_BUILD_ID "{build_id}"\n'
                      f'#define SAMPLE_STATUS "{status}"\n')
    toolchain = args.toolchain.resolve(strict=True)
    with (output / 'sample-build.log').open('w') as log:
        for target in ('clean', 'all'):
            subprocess.run(['make', f'AGONDEV_TOOLCHAIN={toolchain}', target],
                           cwd=project, stdout=log, stderr=subprocess.STDOUT, check=True)
    after = {'commit': git('rev-parse', 'HEAD'), 'dirty': bool(git('status', '--porcelain')),
             'source_sha256': snapshot()}
    if before != after:
        raise SystemExit('Source changed during sample build; no bundle frozen')
    files = []
    for suffix in ('bin', 'map'):
        source = project / ('bin/VTEXT.' + suffix)
        if suffix != 'map':
            verify_embedded_identity(source, source_identity, build_id, status)
        destination = output / (build_id + '-sample.' + suffix)
        shutil.copyfile(source, destination)
        files.append({'filename': destination.name, 'sha256': sha(destination),
                      'size_bytes': destination.stat().st_size, 'role': suffix})
    binary = output / files[0]['filename']
    if binary.read_bytes()[0x40:0x45] not in (b'MOS\x00\x01', b'MOS\x01\x01'):
        raise SystemExit('Missing MOS ADL executable header')
    (output / 'autoexec.txt').write_bytes(b'VDU 22 3\r\nLOAD /bin/VTEXT.BIN\r\nRUN\r\n')
    manifest = {'schema_version': 1, 'build': {'artifact_id': identity['artifact_id'],
                'source_identity': source_identity, 'build_id': build_id, 'status': status,
                'variant': 'sample', 'created_at': now.isoformat()}, 'provenance': before,
                'compiler_sha256': sha(toolchain / 'bin/ez80-none-elf-clang'), 'outputs': files,
                'requires': 'EMOS resident edu.text-probe gateway; introduced in agon-emos-v0.1.7',
                'notes': ['Independent SD application; no UART/GPIO access or mode switch.',
                          'Local build only; no emulator or hardware qualification.']}
    (output / 'build-manifest.yaml').write_text(yaml.safe_dump(manifest, sort_keys=False))
    print('SD sample build PASS: ' + str(output))


if __name__ == '__main__':
    main()
