#!/usr/bin/env python3
"""Compile the paired PORT-009 diagnostic. Never access hardware or removable media.

The same generated contract feeds both processors. Unapproved identity produces
explicit UNVERSIONED-DO-NOT-DEPLOY diagnostics, never a deployment candidate.
"""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import yaml

ROOT = Path(__file__).resolve().parents[1]
MESSAGE = b"EMOS UART1 -> P4\r\n"


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def git(repo, *args):
    return subprocess.check_output(["git", "-C", str(repo), *args], text=True).strip()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--emos", type=Path, default=ROOT.parent / "agon-emos")
    args = parser.parse_args()
    output = args.output.absolute()
    if output.exists(): parser.error("output directory already exists")
    emos = args.emos.resolve(strict=True)
    fixture = emos / "projects/uart-forward"
    toolchain = (ROOT.parent / "mos-agondev/toolchains/agondev").resolve(strict=True)
    identity = json.loads((ROOT / "docs/tasks/PORT-009/identity.json").read_text())
    if identity["status"] not in ("draft", "experimental", "candidate"):
        parser.error("unexpected diagnostic lifecycle status")
    source_identity = identity["source_identity"]
    now = datetime.now(timezone.utc)
    build_id = None
    if source_identity is not None:
        if not re.fullmatch(r"uart-forward-probe-r(?:0[1-9]|[1-9][0-9]+)", source_identity):
            parser.error("unexpected fixture identity")
        build_id = source_identity + now.strftime("-b%Y-%m-%d-%H-%M-%SZ")
    owners = {"extender": ROOT, "emos": emos}
    before = {name: {"commit": git(path, "rev-parse", "HEAD"),
                     "dirty": bool(git(path, "status", "--porcelain"))}
              for name, path in owners.items()}
    if identity["status"] == "candidate" and (not build_id or any(x["dirty"] for x in before.values())):
        parser.error("candidate needs an approved identity and clean committed owners")
    output.mkdir(parents=True)
    display_id = build_id or "UNVERSIONED-DO-NOT-DEPLOY"
    status = identity["status"]
    header = ("// Generated by prepare_uart_forward.py; do not edit.\n"
              f"#define UART_FORWARD_BUILD_ID {json.dumps(display_id)}\n"
              f"#define UART_FORWARD_STATUS {json.dumps(status)}\n"
              "#define UART_FORWARD_BAUD 115200\n"
              f"#define UART_FORWARD_MESSAGE {json.dumps(MESSAGE.decode('ascii'))}\n")
    for path in (fixture / "build/uart_forward_probe_config.h",
                 ROOT / "vdp/.pio/uart-forward/uart_forward_probe_config.h"):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(header)
    (output / "uart_forward_probe_config.h").write_text(header)

    def run(argv, name, cwd=ROOT):
        print(name + ": " + " ".join(map(str, argv[:3])), flush=True)
        with (output / name).open("w") as log:
            log.write(json.dumps(list(map(str, argv))) + "\n"); log.flush()
            result = subprocess.run(list(map(str, argv)), cwd=cwd,
                                    stdout=log, stderr=subprocess.STDOUT)
        if result.returncode:
            print((output / name).read_text()[-5000:], file=sys.stderr)
            raise SystemExit(result.returncode)

    run(["c++", "-std=c++17", "-Wall", "-Wextra", "-Werror", "-fsanitize=address,undefined",
         "-I", ROOT / "vdp/video/extender/diagnostic", ROOT / "tests/uart_forward_match_test.cpp",
         "-o", output / "matcher-test"], "host-build.log")
    run([output / "matcher-test"], "host-test.log")
    run(["make", "clean"], "sender-clean.log", fixture)
    run(["make", f"AGONDEV_TOOLCHAIN={toolchain}", "all"], "sender-build.log", fixture)
    # Check the actual linked binary, not just the installed header comment.
    # AgonDev b67ab244's uputc wrapper returns 0 for carry-set success. The
    # caller compensates; a changed wrapper must trigger deliberate review.
    sender = (fixture / "bin/U1SEND.bin").read_bytes()
    link_map = (fixture / "bin/U1SEND.map").read_text()
    wrappers = {"_mos_uputc": "d1e3d54d3e185bcf3e013001afc9",
                "_mos_uopen": "dde5dd21000000dd39dd37063e155bcfdde1c9",
                "_mos_uclose": "3e165bcfc9"}
    for symbol, expected in wrappers.items():
        found = re.search(r"0x([0-9a-f]+)\s+" + symbol + r"\s*$", link_map, re.M)
        if not found: raise SystemExit("missing linked MOS wrapper: " + symbol)
        offset = int(found.group(1), 16) - 0x40000
        if offset < 0 or sender[offset:offset + len(expected) // 2].hex() != expected:
            raise SystemExit("linked MOS wrapper changed: " + symbol)
    (output / "sender-linked-check.json").write_text(json.dumps({
        "sender_sha256": sha(fixture / "bin/U1SEND.bin"), "wrappers": wrappers,
        "uputc_zero_means_success": True}, indent=2) + "\n")
    print("Linked sender UART API wrappers verified (including zero-success convention)", flush=True)
    run([ROOT / ".venv/bin/pio", "run", "-d", ROOT / "vdp", "-e", "p4-uart-forward"], "receiver-build.log")
    p4 = ROOT / "vdp/.pio/build/p4-uart-forward"
    description = json.loads((p4 / "project_description.json").read_text())
    selected = description["build_component_info"]["video"]["sources"]
    expected_source = str(ROOT / "vdp/video/extender/diagnostic/uart_forward_receiver.cpp")
    if selected != [expected_source]:
        raise SystemExit("P4 application source closure is not the RX-only receiver")
    sdk = (p4 / "config/sdkconfig.h").read_text()
    required_config = ["CONFIG_ESPTOOLPY_FLASHMODE_QIO 1", "CONFIG_ESPTOOLPY_FLASHFREQ_80M 1",
                       "CONFIG_ESPTOOLPY_FLASHSIZE_16MB 1", "CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ 360",
                       "CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG 1", "CONFIG_FREERTOS_HZ 1000",
                       "CONFIG_ESP_REV_MIN_FULL 100", "CONFIG_ESP_REV_MAX_FULL 199"]
    for item in required_config:
        if "#define " + item + "\n" not in sdk:
            raise SystemExit("P4 effective configuration changed: " + item)
    # IDF deliberately stamps DIO in a QIO bootloader header, then enables
    # quad mode during startup (esptool_py/Kconfig.projbuild). Preserve bytes;
    # never override a frozen factory image's header during deployment.
    factory = (p4 / "firmware.factory.bin").read_bytes()
    for name, offset in (("bootloader.bin", 0x2000), ("partitions.bin", 0x8000),
                         ("firmware.bin", 0x20000)):
        data = (p4 / name).read_bytes()
        if factory[offset:offset + len(data)] != data:
            raise SystemExit("factory image differs from built component: " + name)
    (output / "receiver-config-check.json").write_text(json.dumps({
        "source": "video/extender/diagnostic/uart_forward_receiver.cpp",
        "required_sdkconfig": required_config, "sdkconfig_sha256": sha(p4 / "config/sdkconfig.h"),
        "factory_base": "0x0", "factory_application_offset": "0x20000",
        "factory_components_match": True}, indent=2) + "\n")
    for name, path in owners.items():
        if git(path, "rev-parse", "HEAD") != before[name]["commit"]:
            raise SystemExit("owner commit changed during build")
        if identity["status"] == "candidate" and git(path, "status", "--porcelain"):
            raise SystemExit("candidate inputs changed during build")
    files = []
    prefix = build_id or "UNVERSIONED"
    sources = [(fixture / "bin/U1SEND.bin", prefix + "-sender.bin", "sender"),
               (fixture / "bin/U1SEND.map", prefix + "-sender.map", "sender_map"),
               (ROOT / "vdp/.pio/build/p4-uart-forward/firmware.bin", prefix + "-receiver.bin", "receiver"),
               (p4 / "firmware.factory.bin", prefix + "-receiver.factory.bin", "receiver_factory"),
               (p4 / "firmware.elf", prefix + "-receiver.elf", "receiver_elf")]
    for source, name, role in sources:
        dest = output / name; shutil.copyfile(source, dest)
        files.append({"filename": name, "role": role, "size_bytes": dest.stat().st_size, "sha256": sha(dest)})
    sd = output / "sdcard"; (sd / "bin").mkdir(parents=True)
    shutil.copyfile(output / files[0]["filename"], sd / "bin/U1SEND.BIN")
    (sd / "autoexec.txt").write_bytes(b"VDU 22 3\r\nEMOS STATUS\r\nLOAD /bin/U1SEND.BIN\r\nRUN\r\nEMOS STATUS\r\n")
    selected_inputs = {"extender": ["vdp/platformio.ini", "vdp/sdkconfig.defaults", "vdp/partitions.csv",
                        "vdp/boards/olimex_esp32_p4_devkit.json", "vdp/pio/select_sources.py",
                        "vdp/pio/p4-uart-forward-source-selection.json",
                        "vdp/video/extender/diagnostic/uart_forward_receiver.cpp",
                        "vdp/video/extender/diagnostic/uart_forward_match.hpp",
                        "tests/uart_forward_match_test.cpp", "scripts/prepare_uart_forward.py",
                        "docs/tasks/PORT-009/identity.json"],
                       "emos": ["projects/uart-forward/src/main.c", "projects/uart-forward/Makefile"]}
    for name, names in selected_inputs.items():
        before[name]["source_sha256"] = {path: sha(owners[name] / path) for path in names}
    manifest = {"schema_version": 1,
                "build": {"artifact_id": identity["artifact_id"], "source_identity": source_identity,
                          "build_id": build_id, "status": status, "variant": None,
                          "created_at": now.strftime("%Y-%m-%dT%H:%M:%SZ")},
                "provenance": before,
                "toolchain": {"ez80_compiler_sha256": sha(toolchain / "bin/ez80-none-elf-clang"),
                              "ez80_libagon_sha256": sha(toolchain / "lib/libagon.a")},
                "contract": {"baud": 115200, "format": "8N1", "flow_control": False,
                             "message_hex": MESSAGE.hex(), "message_length": len(MESSAGE)},
                "outputs": files, "header_sha256": sha(output / "uart_forward_probe_config.h"),
                "notes": ["Compile and host-test evidence only; no hardware pass.",
                          "Retain unchanged installed EMOS; do not flash an EMOS image."]}
    (output / "build-manifest.yaml").write_text(yaml.safe_dump(manifest, sort_keys=False))
    print("Paired diagnostic: " + str(output))


if __name__ == "__main__":
    main()
