[platformio]
src_dir = src
boards_dir = boards
packages_dir = ../../../../vdp/.pio/packages

[env:reference]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/3.3.11/esp32-core-3.3.11.tar.xz
board = olimex_esp32_p4_devkit
framework = arduino, espidf
board_build.sdkconfig_defaults = sdkconfig.defaults
board_build.partitions = partitions.csv
build_flags = -std=gnu++17
