# Isolated experiment: replace exactly one pinned translation unit in this build.
idf_component_get_property(lcd_dir esp_lcd COMPONENT_DIR)
idf_component_get_property(lcd_target esp_lcd COMPONENT_LIB)
set(original "${lcd_dir}/dsi/esp_lcd_panel_dpi.c")
set(derived "${CMAKE_BINARY_DIR}/dsi-strip/esp_lcd_panel_dpi.c")
execute_process(COMMAND "${PYTHON}" "${CMAKE_CURRENT_LIST_DIR}/patch_dpi.py" "${original}" "${derived}" COMMAND_ERROR_IS_FATAL ANY)
get_target_property(lcd_sources "${lcd_target}" SOURCES)
set(selected)
set(replacements 0)
foreach(source IN LISTS lcd_sources)
  if(IS_ABSOLUTE "${source}")
    set(absolute "${source}")
  else()
    set(absolute "${lcd_dir}/${source}")
  endif()
  if(absolute STREQUAL original)
    list(APPEND selected "${derived}")
    math(EXPR replacements "${replacements}+1")
  else()
    list(APPEND selected "${source}")
  endif()
endforeach()
if(NOT replacements EQUAL 1)
  message(FATAL_ERROR "DPI derivative did not replace exactly one source")
endif()
set_property(TARGET "${lcd_target}" PROPERTY SOURCES "${selected}")
target_include_directories("${lcd_target}" PRIVATE "${lcd_dir}/dsi" "${CMAKE_CURRENT_LIST_DIR}")
if(AGON_HDMI_TIMING STREQUAL "auto")
  target_compile_definitions("${lcd_target}" PRIVATE AGON_EXTENDER_HDMI_AUTO=1)
elseif(AGON_HDMI_TIMING STREQUAL "512x384")
  # The derived C DMA driver and the application must select identical geometry.
  target_compile_definitions("${lcd_target}" PRIVATE AGON_EXTENDER_HDMI_512X384=1)
elseif(AGON_HDMI_TIMING STREQUAL "684x384")
  target_compile_definitions("${lcd_target}" PRIVATE AGON_EXTENDER_HDMI_684X384=1)
elseif(NOT AGON_HDMI_TIMING STREQUAL "848x480")
  message(FATAL_ERROR "Rolling scanout requires an explicit supported geometry")
endif()
idf_component_get_property(timer_dir esp_timer COMPONENT_DIR)
target_include_directories("${lcd_target}" PRIVATE "${timer_dir}/include")
