#!/usr/bin/env python3
"""Validate reviewed SETUP-004 records and generate deterministic projections."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys
from typing import Any

import yaml


GENERATOR_VERSION = "1.0.0"
DISPOSITIONS = {"retain", "replace", "stub", "omit", "defer"}
REQUIRED_RECORD_FIELDS = (
    "id",
    "name",
    "layer",
    "scope",
    "upstream_owner",
    "source_files",
    "implementation_form",
    "facilities",
    "activation",
    "connections",
    "visible_behavior",
    "physical_owner",
    "disposition",
    "rationale",
    "omission_fallout",
    "dependencies",
    "evidence_ids",
    "graph_node_ids",
    "agent_entry_points",
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a YAML mapping")
    return data


def require_string(value: Any, location: str) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{location}: expected a non-empty string")


def validate_record(
    record: dict[str, Any],
    location: str,
    work_item: str,
    evidence_ids: set[str],
    node_ids: set[str],
) -> None:
    missing = [field for field in REQUIRED_RECORD_FIELDS if field not in record]
    if missing:
        raise ValueError(f"{location}: missing fields: {', '.join(missing)}")
    for field in ("id", "name", "layer", "scope", "upstream_owner", "physical_owner", "rationale", "omission_fallout"):
        require_string(record[field], f"{location}.{field}")
    if record["disposition"] not in DISPOSITIONS:
        raise ValueError(f"{location}.disposition: invalid value {record['disposition']!r}")
    for field in (
        "source_files",
        "facilities",
        "activation",
        "visible_behavior",
        "dependencies",
        "evidence_ids",
        "graph_node_ids",
        "agent_entry_points",
    ):
        if not isinstance(record[field], list):
            raise ValueError(f"{location}.{field}: expected a list")
    if not record["source_files"] or not record["evidence_ids"] or not record["graph_node_ids"]:
        raise ValueError(f"{location}: source_files, evidence_ids, and graph_node_ids may not be empty")
    implementation = record["implementation_form"]
    if not isinstance(implementation, dict) or set(implementation) != {"selected_translation_units", "header_implementation"}:
        raise ValueError(f"{location}.implementation_form: expected selected_translation_units and header_implementation")
    connections = record["connections"]
    expected_connections = {"startup", "tasks", "interrupts", "callbacks", "global_state"}
    if not isinstance(connections, dict) or set(connections) != expected_connections:
        raise ValueError(f"{location}.connections: expected {sorted(expected_connections)}")
    unknown_evidence = sorted(set(record["evidence_ids"]) - evidence_ids)
    if unknown_evidence:
        raise ValueError(f"{location}: unknown PORT-001 evidence IDs: {unknown_evidence}")
    unknown_nodes = sorted(set(record["graph_node_ids"]) - node_ids)
    if unknown_nodes:
        raise ValueError(f"{location}: unknown PORT-001 graph node IDs: {unknown_nodes}")
    record["work_item"] = work_item


def md_escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def first_sentence(value: str) -> str:
    compact = " ".join(value.split())
    split = compact.find(". ")
    return compact if split < 0 else compact[: split + 1]


def render_matrix(records: list[dict[str, Any]], input_digest: str) -> str:
    lines = [
        "<!-- Generated by scripts/generate-subsystem-inventory.py; do not hand-edit. -->",
        "# SETUP-004 provisional disposition matrix",
        "",
        "Every disposition remains provisional until Author review. Detailed evidence and",
        "agent entry points are in `generated/subsystem-inventory.yaml`.",
        "",
        f"Input digest: `{input_digest}`",
        "",
        "| Work | Candidate | Layer | Physical owner | Disposition | Provisional rationale |",
        "|---|---|---|---|---|---|",
    ]
    for record in records:
        lines.append(
            "| "
            + " | ".join(
                md_escape(value)
                for value in (
                    record["work_item"],
                    record["name"],
                    record["layer"],
                    record["physical_owner"],
                    record["disposition"].upper(),
                    first_sentence(record["rationale"]),
                )
            )
            + " |"
        )
    lines.extend(("", "## Coverage", ""))
    by_work: dict[str, int] = {}
    for record in records:
        by_work[record["work_item"]] = by_work.get(record["work_item"], 0) + 1
    for work_item, count in sorted(by_work.items()):
        lines.append(f"- `{work_item}`: {count} candidates inventoried")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    script_path = Path(__file__).resolve()
    task_root = script_path.parent.parent
    project_root = task_root.parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--task-root", type=Path, default=task_root)
    parser.add_argument(
        "--graph",
        type=Path,
        default=project_root / "docs/tasks/PORT-001/generated/code-graph.yaml",
    )
    args = parser.parse_args()

    task_root = args.task_root.resolve()
    graph_path = args.graph.resolve()
    evidence_paths = sorted((task_root / "evidence").glob("work-*.yaml"))
    if not evidence_paths:
        raise ValueError(f"{task_root / 'evidence'}: no work evidence files found")

    graph = load_yaml(graph_path)
    if graph.get("artifact_kind") != "code_graph":
        raise ValueError(f"{graph_path}: expected PORT-001 code_graph")
    graph_evidence_ids = {item["id"] for item in graph.get("evidence", [])}
    graph_node_ids = {item["id"] for item in graph.get("nodes", [])}
    graph_sources = {
        item["owner"]: {"identity": item["identity"], "commit": item.get("commit")}
        for item in graph.get("sources", [])
    }

    records: list[dict[str, Any]] = []
    seen_record_ids: set[str] = set()
    input_entries: list[dict[str, str]] = []
    covered_work_items: list[str] = []
    target_frameworks: list[dict[str, Any]] = []

    for evidence_path in evidence_paths:
        reviewed = load_yaml(evidence_path)
        if reviewed.get("schema_version") != 1:
            raise ValueError(f"{evidence_path}: unsupported schema_version")
        work_item = reviewed.get("work_item")
        require_string(work_item, f"{evidence_path}.work_item")
        if not work_item.startswith("SETUP-004.1."):
            raise ValueError(f"{evidence_path}.work_item: expected SETUP-004.1.<letter>")
        covered_work_items.append(work_item)

        sources = reviewed.get("sources", {})
        for key, owner in (("agon_vdp", "agon-vdp"), ("vdp_gl", "vdp-gl")):
            source = sources.get(key, {})
            expected = graph_sources.get(owner)
            if not expected or source.get("release") != expected["identity"] or source.get("commit") != expected["commit"]:
                raise ValueError(f"{evidence_path}.sources.{key}: does not match PORT-001 graph source")

        target_framework = reviewed.get("target_framework")
        if target_framework:
            target_frameworks.append(target_framework)
        reviewed_records = reviewed.get("records")
        if not isinstance(reviewed_records, list) or not reviewed_records:
            raise ValueError(f"{evidence_path}.records: expected a non-empty list")
        for index, record in enumerate(reviewed_records):
            if not isinstance(record, dict):
                raise ValueError(f"{evidence_path}.records[{index}]: expected a mapping")
            validate_record(
                record,
                f"{evidence_path}.records[{index}]",
                work_item,
                graph_evidence_ids,
                graph_node_ids,
            )
            if record["id"] in seen_record_ids:
                raise ValueError(f"duplicate record ID: {record['id']}")
            seen_record_ids.add(record["id"])
            records.append(record)
        input_entries.append(
            {
                "path": evidence_path.relative_to(project_root).as_posix(),
                "sha256": sha256(evidence_path),
            }
        )

    records.sort(key=lambda item: (item["work_item"], item["id"]))
    input_digest = hashlib.sha256(
        "".join(f"{item['path']}:{item['sha256']}\n" for item in input_entries).encode()
    ).hexdigest()
    output = {
        "schema_version": 1,
        "artifact_kind": "setup_004_subsystem_inventory",
        "generator": {
            "name": "generate-subsystem-inventory",
            "version": GENERATOR_VERSION,
            "path": script_path.relative_to(project_root).as_posix(),
            "regeneration_command": ".venv/bin/python docs/tasks/SETUP-004/scripts/generate-subsystem-inventory.py",
        },
        "inputs": {
            "reviewed": input_entries,
            "combined_sha256": input_digest,
            "port_001_graph": {
                "path": graph_path.relative_to(project_root).as_posix(),
                "id": graph["id"],
                "sha256": sha256(graph_path),
            },
        },
        "sources": graph.get("sources", []),
        "target_frameworks": target_frameworks,
        "coverage": {
            "completed_work_items": sorted(set(covered_work_items)),
            "record_count": len(records),
            "status": "provisional_pending_author_review",
        },
        "records": records,
    }

    generated_dir = task_root / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)
    inventory_path = generated_dir / "subsystem-inventory.yaml"
    inventory_path.write_text(
        "# Generated by scripts/generate-subsystem-inventory.py; do not hand-edit.\n"
        + yaml.safe_dump(output, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8",
    )
    (task_root / "disposition-matrix.md").write_text(
        render_matrix(records, input_digest), encoding="utf-8"
    )
    print(f"generated {inventory_path.relative_to(project_root)} with {len(records)} records")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, ValueError, yaml.YAMLError) as error:
        print(f"error: {error}", file=sys.stderr)
        sys.exit(1)

